### ISSUE TITLE
mumax leaks host memory

### ISSUE THREAD

**Issue by godsic** [mumax/3#100]
I have recently observed that our compute nodes going out-of-memory. It turns out mumax leaks some host memory with 0.5-1 MB/s rate (as could be seen from RES reported by top). I can track the leak down to v3.9.1, but cannot really go further because of the major tool chain incompatibilities. It seems like leak is not related to neither go or cuda versions (tried go1.6/1.7/1.8 and cuda7.5/8). Also tried to profile with pprof, but cannot see anything suspicions (see the cpu and mem reports attached). Moreover mumax3 still leaks with GOGC=1. So the issue appears to be on the cgo side...
 
[mumax.pprof.reports.zip](https://github.com/mumax/3/files/841434/mumax.pprof.reports.zip)

**Comment by barnex** [comment]
@godsic : could you post an input file that goes out of memory for you?

**Comment by godsic** [comment]
@barnex attached.
It seems like bug is NVidia driver related. mumax3 leaks only with the recent 378.xx version, but not with the 375.xx one. So it appears that cudart does something nasty with go pointers...
i will suggest users over the mainling list not to use 378.xx branch.

[leak.mx3.txt](https://github.com/mumax/3/files/841645/leak.mx3.txt)

**Comment by godsic** [comment]
@barnex @JLeliaert Sorry to say, but mumax3 leaks memory. feature/nonlocalRKKY branch does not leak. bisect a year of commits?

**Comment by godsic** [comment]
@barnex @JLeliaert The leak in ext_topologicalcharge is introduced in b0dcb11327ea9c1b91f41ffab305c0695f358a12

**Comment by JLeliaert** [comment]
Could it be a defer statement is missing around line 23 in engine/ext_topologicalcharge.go ?

**Comment by JLeliaert** [comment]
Could it be a defer statement is missing around line 23 in
engine/ext_topologicalcharge.go
<https://github.com/mumax/3/commit/b0dcb11327ea9c1b91f41ffab305c0695f358a12#diff-ca1d7a45405954b2f091192d68d9de7a>
?

**Comment by godsic** [comment]
fixed in cd2eeacca53d36654f3b4e3d856546345401dc98

**Comment by JLeliaert** [comment]
Does this mean the 378.xx drivers are safe to use?

**Comment by godsic** [comment]
@JLeliaert needs testing
