### ISSUE TITLE
mumax3 on cuda 8.0

### ISSUE THREAD

**Issue by hsuxx295** [mumax/3#101]
Hi,
I tried to run Mumax 3.8final on a computer with CUDA 8.0.
However I've seen the error 
"error while loading shared libraries: libcufft.so.7.0: cannot open shared object file: No such file or directory"
However I don't have sudo permission. Is there any solution for this?
Thanks

**Comment by barnex** [comment]
It seems like you're using a version that was compiled for cuda7. You should either install cuda7 or re-compile mumax from source.
