### ISSUE TITLE
E_total and DMI

### ISSUE THREAD

**Issue by kleinpoe** [mumax/3#105]
I have a 2D system with direct exchange + DMI (disable dipolar fields). I manually prepare spin helices and vary their wavelength to find an energy minimum. I just vary the wavelength and save the table with E_total (no relax, run etc). It seems E_total/E_exch is not affected by Dbulk. Then I set Aex to a very small value and the resulting energies are 0 for any spin helix wavelength. Did I miss anything or is it a bug?

Thank you,
Simon

example script:

```
D := 1.51260E-1//1.51260E-4
Ms := 111.348e3
A := 6.013212895E-30//6.013212895E-13

// Set parameters
Msat  = Ms
Aex   = A
Dbulk = 1.51260E-1
alpha = 0.004

// Disable Demag field
noDemagSpins=1

// Custom Parameters
ll:=0.0

// Setup Table
TableAdd(Aex)
TableAdd(Dbulk)
TableAdd(B_ext)
TableAdd(E_total)
TableAdd(E_exch)
TableAddVar(ll,"lambda","nm")


l_helix := 4.0*pi*A/D
a_sk := 2.0 / sqrt(3) * l_helix; 

N := 256
nx := N
ny := N
nz := 1

d_x :=  2 * a_sk / N
d_y := 2 * l_helix / N

SetGridSize(nx, ny, nz)
SetCellSize(d_x, d_y, d_x)
SetPBC(0,0,5)

phi:=0.

for BB:=0.0;BB<4;BB+=0.05{

// ----------- CREATE HELIX -------------
phi=0.
for j:=0; j<ny; j++{
for x:=0; x < nx; x++{
DefRegionCell(1,x,j,0)
}
phi = (j/ny)*2.0*pi*BB
m.setregion(1,Uniform(cos(phi),0,sin(phi)))
for x:=0; x < nx; x++{
DefRegionCell(0,x,j,0)
}
}
ll = BB*d_y*ny
// ------------ HELIX end ---------

//saveas(m,"initial config")
save(m)
tablesave()
}
```

**Comment by JeroenMulkers** [comment]
`E_exch` includes both the exchange and the DMI energy. The only interactions considered in this simulation are the exchange interaction and the DMI. This means that `E_total = E_exch`, yielding the trivial ratio `E_total/E_exch = 1`.

In this script, the cell size is proportional to `A`. Consequently, if you make `A` very small, then the dimensions of your ferromagnet will be small, which leads to the very small total energy which you observe.

You will get significant different energies for a helix (with fixed wavelength) in a ferromagnets of the same size but with different DMI strengths.

**Comment by kleinpoe** [comment]
Thank you, I'm sorry for not considering this enough...
