### ISSUE TITLE
Why wrong demag fields when using PBC

### ISSUE THREAD

**Issue by hskur** [mumax/3#107]
When checking the the magnitude of the demagnetizing field in the absence of an external magnetic field and using 1D PBC, I obtain values which disagree with expectation. 

Example:
Nx := 25000
Ny := 4
Nz := 1

Dimx := 80e-6
Dimy := 8e-9
Dimz := 10e-9

SetGridsize(Nx, Ny, Nz)
SetCellsize(Dimx/Nx, Dimy/Ny, Dimz/Nz)

SetPBC(0,2000,0) //periodic boundary condition

alpha = 0.0016
Msat  = 2.4/(4*Pi*1E-7)
Aex   = 2*13e-12
angle := 90

m = uniform(cos(angle/360*2*Pi),sin(angle/360*2*Pi),0)
print(B_demag)

Here, although m points along the y-direction, the demag field along this direction is +2.6 mT. The same situation, when m points along the x-direction. Once again a positive demag field along this direction.

Any idea why this problem occurs and how it can be solved?

Note: Without any PBC the  demag values agree with expectation/calculation.

**Comment by barnex** [comment]
Convergence in your example is indeed not perfect.

Some observations:
  * using a power-of-two grid size makes accuracy better
  * you are using an exceptional aspect ratio 25000:4. I notice convergence is much better with a more reasonable aspect ratio like 2560:4. mumax was designed for 2D and 3D geometries, not for quasi 1D aspect ratios, say over 1000:1
  * convergence is also better with more cubic like cells.

With cubic cells and aspect ratio 2560:4, I notice the demag field correctly converges towards 0 when increasing the repetition (10, 100, 1000).

So it seems your quasi-1D example is hitting the limit of kernel accuracy + floating point precision + CUDA FFT accuracy for extremely elongated geometries. Such edge cases will probably never be fully accurate with mumax as it was not intended to solve those.
