### ISSUE TITLE
Issues compiling Mumax3 on AWS instance

### ISSUE THREAD

**Issue by Lizatre** [mumax/3#109]
I am trying to run mumax3 simulations on an Amazon Instance after changing the mumax3 source code (specifically some files within the engine module). However, I am not able to recompile Mumax3 with the changes.

I started out using the [MIT mucloud](http://ralph-group.github.io/mucloud/) software which provides an AWS Image with the mumax3 binaries loaded in already. After adding my changes I attempted to build the code from the 'src/' directory on the instance, however, I started getting GPU incompatibility problems:
nvcc fatal   : Unsupported gpu architecture 'compute_52'

and also:

cmd/mumax3-fft/spatial.go:10:2: cannot find package "github.com/barnex/matrix" in any of:
    /usr/lib/go/src/pkg/github.com/barnex/matrix (from $GOROOT)
    /home/ubuntu/src/github.com/barnex/matrix (from $GOPATH)

I've also tried compiling the binaries myself (following the directions on the mumax3 readme) on an Amazon instance using the [AWS Marketplace Nvidia-Cuda Image](https://aws.amazon.com/marketplace/pp/B01LZMLK1K). However, on that OS I was not able to install all the necessary dependencies, including go or nvidia-cuda-toolkit.

Perhaps it would be a good idea to make another AMI with my source code but I will still need to recompile the binaries.

I was wondering if you have any pointers about dealing with this issue? Thank you!

**Comment by barnex** [comment]
1) cannot find package "github.com/barnex/matrix: You are compiling mumax3-fft, while you only need to compile mumax3. Just run `go install github.com/mumax/3/cmd/mumax3`, don't compile the other executables.

2) either use a recent nvcc that supports compute 5.2, or remove '52' from cuda/make.bash
