### ISSUE TITLE
Issues with stacking and adding cuboid geometry

### ISSUE THREAD

**Issue by kf265** [mumax/3#119]
Hi,
I've been trying to place two cuboids, one on top of the other then using setgeom(a.add(b)) but with no success. I end up with creation of the transducer only.The script I have been using is:
Nx := 512
Ny := 256
Nz := 13
setGridSize(Nx,Ny, Nz)
setCellSize(4e-9, 4e-9, 4e-9)
Transducer:= cuboid(160e-9,800e-9,40e-9).transl(0,0,-6e-9)
Waveguide:= cuboid(2000e-9,160e-9,12e-9).transl(0,0,20e-9)
setgeom( Transducer.add(Waveguide) )

I've tried making them the full height of the grid and translating them to the correct size but that didn't work either. Curiously, the demag field is correct but not the geometry.

Am I doing something obviously wrong here or? Any suggestions would be welcome.

**Comment by syockit** [comment]
Looks fine to me. You did mention the demag is correct. How did you
determine the geometry is wrong?

Try save(geom) and see what it ended up as using mmdisp or muview

2017/08/07 午後9:00 "kf265" <notifications@github.com>:

**Comment by kf265** [comment]
I've been using the GUI to look at it. The magnetisation shown only ever corresponds to one of the cuboids, same with the geometry. I'll have a look at the geom output.

**Comment by kf265** [comment]
I've checked it in oommf and it seems to be correct. The issue must be the with mumax GUI.

**Comment by barnex** [comment]
Closing as the result was correct, only the interpretation of the UI view was problematic. Note that the web UI is intended to provide a quick look. Outputted data is authoritative and should be investigated with the available tools in case of doubt.
