### ISSUE TITLE
Trouble Installing on Windows 10

### ISSUE THREAD

**Issue by Orange45** [mumax/3#120]
Just as a warning right off the bat; I am a student and have little experience with this type of thing. However, I do need to install mumax3 for reasons I don't need to get into. I have had trouble installing this on windows 10 and have had trouble finding a good and clear guide to help with this. If someone could take the time to write a clear and comprehensive guide on how to install this it would be much appreciated.
Thank you in advance.

**Comment by Orange45** [comment]
Update: I have CUDA 8.0 installed and working with my system. I'm not sure how to run Mumax3 still

**Comment by kkingstoun** [comment]
Please send me a private mail : mateusz.zelent@amu.edu.pl. You can find
compiled for Windows new version on mumax.amu.edu.pl

MZ

pon., 14 sie 2017, 23:28 użytkownik Orange45 <notifications@github.com>
napisał:
