### ISSUE TITLE
Compiling in Windows with CUDA 7.5 and 8.0

### ISSUE THREAD

**Issue by DeSanz** [mumax/3#122]
Hi,

Many thanks for supporting this great software, I am trying to build Mumax from source in Windows following the instructions, but getting this error when I run 'go install':

'  C:\Go\src\github.com\mumax\3\cmd\mumax3>go install
' # github.com/mumax/3/cuda/curand
' C:/cuda/v8.0/lib/x64/curand.lib: error adding symbols: File in wrong format
' collect2.exe: error: ld returned 1 exit status
' # github.com/mumax/3/cuda/cu
' C:/cuda/v8.0/lib/x64/cuda.lib: error adding symbols: File in wrong format
' collect2.exe: error: ld returned 1 exit status`

Both CUDA 7.5 and 8.0 give the same error. I have installed Go and a C compiler as you describe in the instructions ( https://github.com/mumax/3 )

Both the 3.9.3 release .zip source and the master .zip downloaded directly from github have given the same error. The files are used without modification except for the cgoflags.go files in cuda\cu, cuda\cufft and cuda\curand to account for the path where CUDA is installed (C:\cuda\v7.5 or C:\cuda\v8.0)

Thanks again,

Dedalo

**Comment by peynmurray** [comment]
It looks like you're having a different compilation error than I did, but I was able to build from scratch on Windows not long ago from the cuda branch. See #86 for more info.

**Comment by DeSanz** [comment]
Thanks so much for the insight, the problem was with the compiler. I was using MinGW instead of MinGW-x64.

For future reference, installing Winbuilds (http://win-builds.org/doku.php/download_and_installation_from_windows) under C:\WinBuilds and adding C:\WinBuilds\bin manually to the system path variable solved the problem.

Best,

Dedalo

**Comment by DeSanz** [comment]
I was too fast claiming that the issue was solved, the compilation runs without errors but the resulting mumax3.exe does nothing when executed. No errors, no output at all.

Any clue of what the issue could be?

**Comment by peynmurray** [comment]
What is the output of mumax3 -test?

**Comment by kkingstoun** [comment]
You have to use a command like this:

mumax3.exe -o "output.out" ./script.mx3

**Comment by DeSanz** [comment]
Thanks for the response,

So these are the outputs of both suggestions (a blank line), I have put a pause in the script because otherwise the command window closes too quickly.

C:\Go\bin>mumax3 -test

C:\Go\bin>pause
Press any key to continue . . .

and

C:\Go\bin>mumax3.exe -o "output.out" ./script.mx3

C:\Go\bin>pause
Press any key to continue . . .

It is just opening and closing very quickly, but the execution is not doing anything... with the second command it should at least complain about not finding script.mx3

I tried compiling an older version using cuda 7.5 and the result is the same, it feels like my compiler is the problem. Which compilers are you using?

**Comment by JSuni** [comment]
i have attached you a file, where i've written down, what i did to get it working on windows 7 64bit.
[setup environment for compiling mumax.txt](https://github.com/mumax/3/files/1269652/setup.environment.for.compiling.mumax.txt)

**Comment by barnex** [comment]
Thanks @JSuni for the explanation. Closing as this seems resolved now. 
Note: the upcoming 3.10 release will include windows binaries for your convenience.
