### ISSUE TITLE
Not Sure Where to put Input Files

### ISSUE THREAD

**Issue by Orange45** [mumax/3#125]
I am relatively new with this software and have been using exclusively the online interface. However, I now need to use an input file. I have tried putting the file in the same directory as the exe, but I am not sure where to go from there. Upon launch it still does not detect a file and I am unable to run the file from the web interface.

**Comment by kahlos** [comment]
Two options. Open windows command line, navigate to the directory and run with `mumax3 myscript.mx3`

Or  you could create a batch file (.bat) in your mumax directory that contains the same command `mumax3 myscript.mx3`. You can then run the .bat file.

**Comment by Orange45** [comment]
Thank you. I got some files to run.
