### ISSUE TITLE
Failing Tests on Latest Compilation

### ISSUE THREAD

**Issue by kahlos** [mumax/3#127]
I've compiled mumax3 on an up to date Arch linux system running 2x 1080 Ti GPU's, driver 384.69 and cuda 8.0.61. Running the tests everything works fine except failure on the following:

**fixedlayer**
`//STtorque[0] :  have:  0.00020790935377590358  want:  0.00020761338237207383 ± 1e-07`

**std5b**
`//m[0] :  have:  -0.953765869140625  want:  -0.9538384675979614 ± 1e-05`

Anyone have any ideas? Is this anything to worry about?

**Comment by barnex** [comment]
This might have something to do with recent STT fixes by @godsic. The result is now possibly more precise, and the tests might have to be adjusted.

**Comment by kahlos** [comment]
Ah yes, that could be it. The other thing I forgot to mention, on an otherwise identical system, but with a Telsa K40c and Quadro K5200, I don't get these failures. I'd presume it's something to do with the latest compute models.

**Comment by godsic** [comment]
@kahlos @barnex I confirm STT-related test with non-zero field-like torque parameter are expected to fail when on the master branch. Hopefully I will find some time soon to make new (OOMMF-based) unit tests.

**Comment by godsic** [comment]
fixedlayer is fixed with a7384f54181f10f763baabc460cb9d59058c91e0

**Comment by godsic** [comment]
std5b is fixed with 0a27edafe1b57f9eb33a752d17aed705a777a0da
