### ISSUE TITLE
mumax3.10 release planning

### ISSUE THREAD

**Issue by godsic** [mumax/3#128]
As @barnex already suggested it appears to be a good time for mumax3.10 release.
Since we have quite some new features and fixes since 3.9.3c it would be nice if can describe them in release notes so people are 100% aware. I guess the easiest part would be @JLeliaert high order and adaptive solvers, since we can point people to the arXiv manuscript. Otherwise, myself and @JeroenMulkers should describe STT- and exchange-related changes, respectively.

I have comprehensive build environment for Linux that covers supported CUDA releases. So I will be able to build a bunch of mumax3 binaries for various CUDA versions. In addition I have Windows 10 virtual machine to provide corresponding mumax3 builds linked to the CUDA8 libraries. So guys let me know how do you feel about releasing mumax3.10?

**Comment by JLeliaert** [comment]
I'd like a new release, but prefer to wait for the publication of the
temperature paper, so it is included in the reference system.
Advanced users can build a binary themselves, and the users who only rely
on the provided binaries will not update after the final publication is
added to the reference system, which I would find regrettable.

Next to that, I'm also working on a few smaller other features that I'd
like to include for which I'll send a pull request also quite soon.

**Comment by barnex** [comment]
OK, what needs to be done:

  * I started a draft release: https://github.com/mumax/3/releases/tag/untagged-a550dd2b59d233cef40d  @all: please add/modify bullet points in the draft release notes.
  * @JLeliaert : any estimate on when the paper might be published?
  * @JLeliaert : which other features do you have upcoming?
  * @godsic : do you plan to fix the STT tests (#127) before this release?
  * I'm reviewing #129, which might be a nice addition too.
  * git tag v3.10
  * @godsic: +1 for offering to build, I really appreciate this.

**Comment by JLeliaert** [comment]
I have added a cross product to the available operations with custom
fields. Together with @JeroenMulkers implemented a 2D moving window (with
identical behavior as in the 1D case for (re)generating (previous) Voronoi
cells), and I implemented an improved bubble position that works more
reliably in the presence of thermal fluctuations and has sub-cellsize
resolution.
All of them work, and with a bit of cleanup could be finished on Monday if
necessary.

I submitted the paper on September 8th to AIP Advances, so conservatively
speaking, this might very well take another 2 months. As this is on a
longer timescale than the other things we're speaking about, I would agree
on not waiting for this if @godsic agrees to update the binaries after
publication?

btw. has anyone checked out #107 <https://github.com/mumax/3/issues/107>? I
could recreate this bug but was unable to fix it.

**Comment by peytondmurray** [comment]
What about merging feature/cuda8 with master? Those of us compiling on Windows would appreciate it, although I think that branch is broken right now, with cuda2go generating an improper slonczewski2_wrapper.go...

**Comment by barnex** [comment]
@godsic : does master need any more work to support cuda8? The original feature branch has gone.
@peytondmurray : could you explain which windows-specific features you appreciate?

**Comment by godsic** [comment]
@barnex Yes it does. There are two issues at least:
- on Windows we need to point cgo to cuda8 folders;
- cuda8 has issues compling kernels with gcc5+. Either we need to use funny nvcc flags to overcome the problem or ask users to use supplied cuda wrappers (with encapsulated PTX)  that we generate under Linux. BTW, cuda9 is free from this issue.

On the side note, yes I will provide new STT unit test before the release.

**Comment by ivlis** [comment]
Any plans for the release?

**Comment by pavankulka** [comment]
Is there any documentation/guide to install mumax on CentOS7? In my environment I don't have internet access to nodes so it would be helpful if I can get the rpm package of the mumax software

**Comment by godsic** [comment]
@JeroenMulkers Are we all set for the release?

**Comment by JeroenMulkers** [comment]
Yes. 

I suggest to run the deploy scripts in the deploy directory. These scripts build mumax3 against different cuda versions and put them in a tar ball with the necessary cuda libraries. These executables can be run without the need to have the cuda libraries/toolkit installed. 

The deploy scripts for windows and linux work on my machine. The deploy script for linux is fairly portable, but I'm not sure about the windows deploy scripts. Is it ok if I create the final build?

**Comment by JeroenMulkers** [comment]
Builds of c7e15a15 (the latest commit at time of writing) can be found [here](http://dynamag.ugent.be/mumax3/download.html) for both linux and windows.

The website will be updated to mumax3.10 if [this pull request](https://github.com/mumax/mumax.github.io/pull/8) is merged.

If there is anything which need to be changed or discussed, I would like to wait with the release until July 10 because I will not have access to any computer until then.

**Comment by godsic** [comment]
@JeroenMulkers Perfect, would you be willing to put stuff together and make an announcement? If so, mumax3.10β announcement already container an extensive list of new features and those should be complemented by all the new ones added since then plus list of contributors should be updated as well.

**Comment by JeroenMulkers** [comment]
@godsic I do not have sufficient time to finish it today. But it will be the first thing which I will do when I am back from holiday.

**Comment by godsic** [comment]
@JeroenMulkers Good, I started mumax3.10 release draft by copy-pasting mumax3.10β one. I will try to update it with things added since β and then you are free to wrap it up once back.

**Comment by godsic** [comment]
@JeroenMulkers @JeroenMulkers Guys, are there any other new features in pipeline or we are ready to release?

**Comment by JeroenMulkers** [comment]
@godsic My appologies for the late answer. We requested server space at the UGent which took some time. We will use this space to host the different mumax3 builds (see 9e0f5061).

I think that we are ready for the release unless you have some comments on the latest commits.

**Comment by godsic** [comment]
No worries. I’ve made a draft of the release (see “Releases”), went through all the relevant history since beta and updated release notes accordingly. Could you please double check those? After that the release can go public if nobody objects. The tag will be created automatically.

**Comment by godsic** [comment]
No worries. I’ve made a draft of the release (see “Releases”), went through all the relevant history since beta and updated release notes accordingly. Could you please double check those? After that the release can go public if nobody objects. The tag will be created automatically.

**Comment by godsic** [comment]
No worries. I’ve made a draft of the release (see “Releases”), went through all the relevant history since beta and updated release notes accordingly. Could you please double check those? After that the release can go public if nobody objects. The tag will be created automatically.

**Comment by godsic** [comment]
No worries. I’ve made a draft of the release (see “Releases”), went through all the relevant history since beta and updated release notes accordingly. Could you please double check those? After that the release can go public if nobody objects. The tag will be created automatically.

**Comment by JeroenMulkers** [comment]
Thank you for updating the release notes. 

I added one more thing to the list: "mumax3-convert can now convert ovf files to numpy binary files"

I will make the release public now.

**Comment by godsic** [comment]
Congratulations everybody 🥳
