### ISSUE TITLE
Building cuda kernels

### ISSUE THREAD

**Issue by JeroenMulkers** [mumax/3#141]
There are two 'makefiles' to build the cuda kernels. Depending on which makefile you use, the cuda version, and maybe other settings, you will end up with different ptx files en wrappers.

What is the recommended way to build modified cuda kernels before incorporating the changes in the master branch?

**Comment by godsic** [comment]
@JeroenMulkers https://github.com/mumax/3/blob/master/cuda/make.bash is something one would run before tagging a release as it generates PTX of the widest GPUs drivers compatibility. Consequently, it needs many CUDA versions co-installed on a build machine. In contrast, https://github.com/mumax/3/blob/master/cuda/make.bash spills PTX using system's default CUDA, which is more practical during development process.

**Comment by barnex** [comment]
Thanks @godsic for clarifying. I'm going to close, working as intended.
