### ISSUE TITLE
Multiple external fields

### ISSUE THREAD

**Issue by jck245** [mumax/3#144]
I want to have a spatially varying, time-dependent external field (to approximate the field from a microstrip line) against a static background field. I've made the fields with vector masks, and it seems that I can only put in the time dependence once I add the mask to B_ext, so I can't just make one mask with both the t-varying and static fields. I found this code https://github.com/mumax/2/blob/master/examples/multifield.py for adding multiple masks, but it's not for the current MuMax version.
What's the right way in MuMax3 to superpose two masks?

Thanks

**Comment by barnex** [comment]
You can add multiple contributions:
B_ext.Add(  field1... )
B_ext.Add(  field2... )
....
Simply make the 2nd term time-independent.
Does that answer your question?
