### ISSUE TITLE
How can I save the magnetization of one cell?

### ISSUE THREAD

**Issue by guanxiongchen** [mumax/3#145]
I have just started to learn mumax3 and tried to use"tableAdd(m.GetCell(1, 0, 0))" to add the magnetization in Cell(1,0,0) to table but it shows" type mismatch: can not use type data.Vector as engine.TableData". I wonder what would be the correct way to save the magnetization in one cell to the table?

Thank you!

**Comment by JeroenMulkers** [comment]
Try this:

`tableaddvar( m.getcell(1,0,0).x(), "mcell_x", "")`

I also suggest that you join our [mailing list](https://groups.google.com/forum/#!forum/mumax2) in which mumax users help each other by asking and answering questions like this one.

**Comment by guanxiongchen** [comment]
Thank you for your help and I have joined the mail list😊

Sincerely;
Guanxiong Chen
