### ISSUE TITLE
MuMax fails to generate correct number of files

### ISSUE THREAD

**Issue by jck245** [mumax/3#153]
Sometimes MuMax will finish its calculation but won't have generated the correct number of files. For example, I tell it to save every 5e-11 seconds and run for a total time of 10e-9, but it generates 120 files instead of 200. I am running it in a command line, and the line exits, so MuMax thinks it is finished. I can get usually get it to complete if I play around with the dimensions and number of cells, but I don't know what's causing this so it's hard to know how to properly adjust the dimensions.
As a more concrete example, with (256x64x32)cells and (200x50x3)um^3 total geometry, I try to save every 5e-11 seconds for 7ns but only generate around 90 ovf files.
Is this a known problem? Is it actually just saving at a larger time interval? I have found that increasing the cell number can help, so is something happening too quickly at a low cell number that causes something in MuMax to skip?

**Comment by JeroenMulkers** [comment]
This can occur when the adaptive time step of the solver is larger than the time interval of the autosave function. 

To avoid this, you could fix the time step of the solver to a value lower than the time interval of the autosave function, or you could simply increase the time interval. I suggest the latter.
