### ISSUE TITLE
Saving functions

### ISSUE THREAD

**Issue by AIrodrigo** [mumax/3#154]
Hello everyone,
I've been trying to save a "geom funct" wchich is going to be used later to create a new one. It could be something like this:

> x:= cylinder(r, r).transl(0, 0, 0)
> y:= cylinder(r2, r2).transl(0, 0, 0)
> z:= rect(r, r).transl(0, 64e-9, 0)
> setgeom( x.sub(y).sub(z) )
> saveas(geom, "S")
> 
> 
> a := cylinder(r, r).transl(-104e-9, 0, 0)
> a2 := cylinder(r2, r2).transl(-104e-9, 0, 0)
> sq:= rect(r, r).transl(-104e-9, -64e-9, 0)
> setgeom(a.sub(a2).sub(sq))
> save(geom,"P")

Here is the issue:
> setgeom( S.add(P))

How can I add this two fucntions (S and P) to create a new one?

Thank you,

Rodrigo

**Comment by schmorlachs** [comment]
Hi Rodrigo,
the easiest solution would be to save the two different geometries as extra variables. 
``x:= cylinder(r, r).transl(0, 0, 0);;
y:= cylinder(r2, r2).transl(0, 0, 0);
z:= rect(r, r).transl(0, 64e-9, 0);
geom1:=x.sub(y).sub(z) ;
setgeom(geom1);
saveas(geom, "S");

a := cylinder(r, r).transl(-104e-9, 0, 0);
a2 := cylinder(r2, r2).transl(-104e-9, 0, 0);
sq:= rect(r, r).transl(-104e-9, -64e-9, 0);
geom2:=a.sub(a2).sub(sq);
setgeom(geom2);
save(geom,"P");
setgeom(geom1.add(geom2));``
Or am I missing a detail?
Best regards
Alex

**Comment by AIrodrigo** [comment]
Hi Alex,

The solution you suggested is perfect, it is exactly what I was looking for. Now I can save the geometries and use them later to create a new one. 
Thank you very much for your help.

Regards,
Rodrigo
