### ISSUE TITLE
Convert .vts-files to .ovf

### ISSUE THREAD

**Issue by schmorlachs** [mumax/3#157]
Hi!
How can I convert some ASCII vts-file to a binary ovf-file? 
This would be useful for instance in order to define a 3D-geometry, which can't be expressed in terms of the standard geometric shapes. So I guess I'm looking for something similar to the ImageShape()-function, but in three dimensions.
Best regards,
Alex

**Comment by JeroenMulkers** [comment]
We do not provide a tool which converts vts-files to ovf-files.

It is straightforward to convert the data of an ovf-file in a vtk structured grid, but not the other way around.

I suggest you get familiar with the ovf format and implement your own converter which fits your needs.
