### ISSUE TITLE
More than only one K1

### ISSUE THREAD

**Issue by Fixtandantilux** [mumax/3#16]
Is it possible to define more than only one K1/anisU pair?
In OOMMF it's possible to add several anisotropies just by naming them separately, so you can define several uniaxial anisotropy axis with different values (ej. K1(001)=1E5J/m3 AND K1(100)=1E3J/m3).
Is there any way to add more than only one anisotropy direction/magnitude?

**Comment by deltaf** [comment]
> If Ka = Ku1(001), Kb = Ku1(100), then I think you can just set AnisU =(Kb/sqrt(Ka²+Kb²), 0, Ka/sqrt(Ka²+Kb²), Ku1 = sqrt(Ka²+Kb²). Unless I'm missing something, that should be equivalent to what you asked for.

The 2nd order anisotropy isn't linear so it wouldn't work: `(u.m)^2 + (v.m)^2 ≠ [(u+v).m]^2`.

This feature would be useful especially in cases where you have hard and easy axis terms simultaneously ---and since they will have different signs, a new term in mumax is needed.

**Comment by alexanderwelbourne** [comment]
I'm wondering if there has been any change on this issue? I'd like to have the same functionality although in my case I would like to be able to simulate the application of a strain being applied at an axis not co-linear to the uniaxial anisotropy. As far as I can see, looking at the latest code, it is still not possible. Is this correct and if so, is there any scope for adding it in? Thanks!

**Comment by JLeliaert** [comment]
In the latest version of mumax it's possible to add custom energy terms, e.g. to define any combination of anisotropies you want. Please have a look at https://github.com/mumax/3/blob/master/test/custom_anisotropy.mx3
