### ISSUE TITLE
initializing an array variable 

### ISSUE THREAD

**Issue by AIrodrigo** [mumax/3#162]
Hello everyone,
I've been trying to create an array in mumax but it's been impossible. I tried using the golang language : x:= [3]float64{0,5,3}... However it always pops up an error message.
How can I initialize an array in mumax3?

Thank you,
Rodrigo

**Comment by JeroenMulkers** [comment]
In your example, you could use `x := vector(0,5,3)`.

The scripting language of mumax3 is not golang (it's at most a very small subset).
However, it is possible to use golang instead of the scripting language.
An example: https://github.com/mumax/3/blob/master/test/standardproblem4.go

**Comment by AIrodrigo** [comment]
Hi Jeroen, thank you very much for your help.  The problema is that from that way you are giving to the vector 3 arguments. However, I need to initialize a string (vector) with many elements (numbers, float64)... x:= [0.1, 0.3, 0.5, etc]. 

Thank you,
Rodrigo

**Comment by JeroenMulkers** [comment]
Then you are probably better of by writing your simulation directly in Go.

**Comment by AIrodrigo** [comment]
Ok, I will try this way. 
Thank you
