### ISSUE TITLE
CURAND_STATUS_LAUNCH_FAILURE when Temperature introduced

### ISSUE THREAD

**Issue by DeSanz** [mumax/3#164]
Hi,
I am trying to introduce temperature using mumax 3.9.1c in Windows but I am getting a  CURAND_STATUS_LAUNCH_FAILURE error. The error only occurs when temperature is introduced.

I have seen that similar issues occurred in the past, did anyone find a solution? Drivers were updated just before the test below (same error before updating drivers).

Thanks in advance

Dedalo

//mumax 3.9.1c windows_amd64 go1.3.3 (gc)
//CUDA 9010 GeForce GTX 1080 Ti(11264MB) cc6.1, using CC53 PTX
//(c) Arne Vansteenkiste, Dynamat LAB, Ghent University, Belgium
//This is free software without any warranty. See license.txt
//output directory: Energy_profile_evaluation_temperature.out/
//starting GUI at http://127.0.0.1:35367
Aex = 1e-11
Msat = 1030000
alpha = 1
OutputFormat = OVF1_TEXT
B_ext = vector(0, 0, 0)
D := 1.001e-06
AR := 0
Mix := 0.5
Relaxed := 0
Nmesh1 := 64
Nmesh2 := 256
Mesh1 := D / Nmesh1
Mesh2 := Mesh1
SetMesh(Nmesh1, Nmesh1, Nmesh2, Mesh1, Mesh1, Mesh2, 0, 0, 0)
Setgeom(cylinder(D, D*100))
// Initializing geometry 0 %
// Initializing geometry 100 %
DefRegion(0, Universe())
DefRegion(1, cylinder(D, D))

tableadd(Temp)
tableAdd(E_total)
tableAdd(E_exch)
tableAdd(E_demag)
tableadd(E_zeeman)

D = 1.3e-07
AR = 7
Nmesh1 = 64
Nmesh2 = 448
Mesh1 = D / Nmesh1
Mesh2 = Mesh1
SetMesh(Nmesh1, Nmesh1, Nmesh2, Mesh1, Mesh1, Mesh2, 0, 0, 0)
//resizing...
Setgeom(cylinder(D, D*100))
DefRegion(0, Universe())
DefRegion(1, cylinder(D, D))
m.LoadFile("test_relaxed.ovf")
SetSolver(4)
FixDt = 1e-15
Temp = 20
Run(1e-9)
//Not using kernel cache (-cache="")
// Calculating demag kernel 49 %
// Calculating demag kernel 100 %
panic: CURAND_STATUS_LAUNCH_FAILURE

goroutine 16 [running]:
runtime.panic(0x8af1a0, 0xc9)
        c:/go/src/pkg/runtime/panic.c:279 +0x11f
github.com/mumax/3/cuda/curand.Generator.GenerateNormal(0x58110b0, 0xb33e00000, 0x1c0000, 0x3f80000000000000)
        C:/Users/Arne/src/github.com/mumax/3/cuda/curand/generator.go:41 +0x7a
github.com/mumax/3/engine.(*thermField).update(0xd9bbc0)
        C:/Users/Arne/src/github.com/mumax/3/engine/temperature.go:99 +0x4ab
github.com/mumax/3/engine.(*thermField).AddTo(0xd9bbc0, 0xc08818c7d0)
        C:/Users/Arne/src/github.com/mumax/3/engine/temperature.go:51 +0x4a
github.com/mumax/3/engine.SetEffectiveField(0xc08818c7d0)
        C:/Users/Arne/src/github.com/mumax/3/engine/effectivefield.go:18 +0xb1
github.com/mumax/3/engine.(*_setter).Set(0xd9bd00, 0xc08818c7d0)
        C:/Users/Arne/src/github.com/mumax/3/engine/setter.go:27 +0x37
github.com/mumax/3/engine.SetLLTorque(0xc08818c7d0)
        C:/Users/Arne/src/github.com/mumax/3/engine/torque.go:58 +0x3b
github.com/mumax/3/engine.SetTorque(0xc08818c7d0)
        C:/Users/Arne/src/github.com/mumax/3/engine/torque.go:51 +0x2e
github.com/mumax/3/engine.torqueFn(0xc08818c7d0)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:93 +0x2e
github.com/mumax/3/engine.(*RK4).Step(0xd9a6a0)
        C:/Users/Arne/src/github.com/mumax/3/engine/rk4.go:39 +0x319
github.com/mumax/3/engine.step(0x7eca01)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:196 +0x3a
github.com/mumax/3/engine.runWhile(0xc082057850, 0x1)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:181 +0x95
github.com/mumax/3/engine.RunWhile(0xc082057850)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:172 +0x40
github.com/mumax/3/engine.Run(0x3e112e0be826d695)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:158 +0x67
reflect.Value.call(0x80d040, 0xa762f0, 0x0, 0x130, 0x971810, 0x4, 0xc082063de0, 0x1, 0x1, 0x0, ...)
        c:/go/src/pkg/reflect/value.go:563 +0x1217
reflect.Value.Call(0x80d040, 0xa762f0, 0x0, 0x130, 0xc082063de0, 0x1, 0x1, 0x0, 0x0, 0x0)
        c:/go/src/pkg/reflect/value.go:411 +0xde
github.com/mumax/3/script.(*call).Eval(0xc0830a4420, 0x0, 0x0)
        C:/Users/Arne/src/github.com/mumax/3/script/call.go:61 +0x25d
github.com/mumax/3/engine.EvalFile(0xc082059bf0)
        C:/Users/Arne/src/github.com/mumax/3/engine/script.go:95 +0x1e7
main.runFileAndServe(0xc082007d40, 0x29)
        C:/Users/Arne/src/github.com/mumax/3/cmd/mumax3/main.go:144 +0x1e1
main.main()
        C:/Users/Arne/src/github.com/mumax/3/cmd/mumax3/main.go:89 +0x2c6

goroutine 17 [syscall, 1 minutes]:
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 19 [finalizer wait, 1 minutes]:
runtime.park(0x41a6a0, 0xd992a0, 0xd97149)
        c:/go/src/pkg/runtime/proc.c:1369 +0xac
runtime.parkunlock(0xd992a0, 0xd97149)
        c:/go/src/pkg/runtime/proc.c:1385 +0x42
runfinq()
        c:/go/src/pkg/runtime/mgc0.c:2644 +0xdd
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive, 1 minutes]:
github.com/mumax/3/engine.runSaver()
        C:/Users/Arne/src/github.com/mumax/3/engine/asyncio.go:40 +0x57
created by github.com/mumax/3/engine.init┬╖2
        C:/Users/Arne/src/github.com/mumax/3/engine/asyncio.go:24 +0xa3

goroutine 33 [IO wait]:
net.runtime_pollWait(0x552f728, 0x72, 0x0)
        c:/go/src/pkg/runtime/netpoll.goc:146 +0x6d
net.(*pollDesc).Wait(0xc08314c770, 0x72, 0x0, 0x0)
        c:/go/src/pkg/net/fd_poll_runtime.go:84 +0x4d
net.(*ioSrv).ExecIO(0xc0830d8128, 0xc08314c660, 0x98f890, 0x8, 0xc085570e60, 0xc0831a2180, 0x0, 0x0)
        c:/go/src/pkg/net/fd_windows.go:188 +0x242
net.(*netFD).acceptOne(0xc08314c600, 0xa76e80, 0xc0820601c0, 0x2, 0x2, 0xc08314c660, 0xe5, 0x0, 0x0)
        c:/go/src/pkg/net/fd_windows.go:546 +0x3c7
net.(*netFD).accept(0xc08314c600, 0xa76e80, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/fd_windows.go:573 +0x187
net.(*TCPListener).AcceptTCP(0xc0830d8138, 0x8, 0x0, 0x0)
        c:/go/src/pkg/net/tcpsock_posix.go:234 +0x64
net.(*TCPListener).Accept(0xc0830d8138, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/tcpsock_posix.go:244 +0x52
net/http.(*Server).Serve(0xc0830e00c0, 0x552e780, 0xc0830d8138, 0x0, 0x0)
        c:/go/src/pkg/net/http/server.go:1698 +0x98
net/http.Serve(0x552e780, 0xc0830d8138, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/pkg/net/http/server.go:1576 +0x83
github.com/mumax/3/engine.func┬╖085()
        C:/Users/Arne/src/github.com/mumax/3/engine/gui.go:537 +0x3f
created by github.com/mumax/3/engine.GoServe
        C:/Users/Arne/src/github.com/mumax/3/engine/gui.go:537 +0x2ea

goroutine 49 [chan send]:
github.com/mumax/3/engine.InjectAndWait(0xc085570e20)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:214 +0xcf
github.com/mumax/3/engine.(*render).download(0xd9d598)
        C:/Users/Arne/src/github.com/mumax/3/engine/render.go:103 +0x6b
github.com/mumax/3/engine.(*render).render(0xd9d598)
        C:/Users/Arne/src/github.com/mumax/3/engine/render.go:109 +0x39
github.com/mumax/3/engine.(*guistate).ServeRender(0xd9d580, 0x154d05a0, 0xc08203e500, 0xc082053a00)
        C:/Users/Arne/src/github.com/mumax/3/engine/render.go:37 +0x8d
github.com/mumax/3/engine.*guistate.ServeRender┬╖fm(0x154d05a0, 0xc08203e500, 0xc082053a00)
        C:/Users/Arne/src/github.com/mumax/3/engine/gui.go:106 +0x4b
net/http.HandlerFunc.ServeHTTP(0xc083187b20, 0x154d05a0, 0xc08203e500, 0xc082053a00)
        c:/go/src/pkg/net/http/server.go:1235 +0x47
net/http.(*ServeMux).ServeHTTP(0xc082058150, 0x154d05a0, 0xc08203e500, 0xc082053a00)
        c:/go/src/pkg/net/http/server.go:1511 +0x1aa
net/http.serverHandler.ServeHTTP(0xc0830e00c0, 0x154d05a0, 0xc08203e500, 0xc082053a00)
        c:/go/src/pkg/net/http/server.go:1673 +0x1a6
net/http.(*conn).serve(0xc083102280)
        c:/go/src/pkg/net/http/server.go:1174 +0xa85
created by net/http.(*Server).Serve
        c:/go/src/pkg/net/http/server.go:1721 +0x31a

goroutine 65 [chan send]:
github.com/mumax/3/engine.func┬╖084()
        C:/Users/Arne/src/github.com/mumax/3/engine/gui.go:443 +0x95
github.com/mumax/3/gui.(*Page).serveUpdate(0xc0820164e0, 0x154d05a0, 0xc08203e6e0, 0xc0878bc1a0)
        C:/Users/Arne/src/github.com/mumax/3/gui/page.go:187 +0x48
github.com/mumax/3/gui.(*Page).ServeHTTP(0xc0820164e0, 0x154d05a0, 0xc08203e6e0, 0xc0878bc1a0)
        C:/Users/Arne/src/github.com/mumax/3/gui/page.go:151 +0x180
net/http.(*ServeMux).ServeHTTP(0xc082058150, 0x154d05a0, 0xc08203e6e0, 0xc0878bc1a0)
        c:/go/src/pkg/net/http/server.go:1511 +0x1aa
net/http.serverHandler.ServeHTTP(0xc0830e00c0, 0x154d05a0, 0xc08203e6e0, 0xc0878bc1a0)
        c:/go/src/pkg/net/http/server.go:1673 +0x1a6
net/http.(*conn).serve(0xc0830d0180)
        c:/go/src/pkg/net/http/server.go:1174 +0xa85
created by net/http.(*Server).Serve
        c:/go/src/pkg/net/http/server.go:1721 +0x31a

**Comment by DeSanz** [comment]
Hi, I could not find a solution, hoping that some update will fix it soon!

**Comment by MartenArthers** [comment]
In the end I got it working!

I now use the 3.10 Beta (found at the top of issue #175) in combination
with CUDA 9.1. The problem I had in the end was that I had installed the
newly released CUDA 9.2 so I had to go back one version.

Hope this works for you,
Marten

2018-05-19 2:35 GMT+02:00 DeSanz <notifications@github.com>:
