### ISSUE TITLE
Space dependent outputs in PNG format do not showing spin magnets for mumax3 example programmes

### ISSUE THREAD

**Issue by sateeshphysicist** [mumax/3#165]
I am new to magnetic simulations. I am learning magnetic simulations using mumax3 in windows10 . I am trying to run the examples programmes which are in the mumax3 website. I am getting the outputs in ovf format and able to convert into png format, but unable to see the magnetic spins in the png out put format just its showing colorful grids . I am unable to find the problem yet. Could you solve this issue asap.

**Comment by JeroenMulkers** [comment]
Try `mumax3-convert -png -arrows 10 m000000.ovf`

**Comment by sateeshphysicist** [comment]
Thank you so much for your reply @ Jeroen Mulkers.
I have tried it but it doesn't worked sir. Even I am also unable to convert
table.txt into gnuplot. For that I tried to plot it in excel and it worked.
So please help me out to solve these two problmes.

**Comment by sateeshphysicist** [comment]
Thank you so much sir its working sorry for earlier mail. And one more
problem sir how to convert tablet.txt into gnuplot.

**Comment by sateeshphysicist** [comment]
Thank you so much Jeroen Mulkers

**Comment by JeroenMulkers** [comment]
Gnuplot is a plotting tool. It does not convert data.
Consult gnuplot's manual if you want to use it.
