### ISSUE TITLE
Gap between thin films

### ISSUE THREAD

**Issue by charliekind** [mumax/3#166]
Dear Mumax3,

I am trying to model thin films with varying spatial (z) gaps between them and also sandwiched antiferromagentic layers and I am not fully understanding what I am doing. I have a couple of questions that I hope someone may have the time to answer.

1. ext_scaleExchange(0, 1, scale)
When I initialise a two layer system with nodemag I get the same results in both layers however I set the ext_scaleExchange: positive, negative or zero (DBulk is on and uniform). The question then is what is calculated between the layers apart from exchange, also if demag is on does the demag kernel calculate the total demag or layer by layer? My layers tend to have differing anisotropy and sometimes DMI.

2. defRegion(2, layers(1, 9))
Next I tried separating the thin films with layers, is this totally the wrong idea, what are these layers, just space, I note that the more layers the longer the calculations per timestep? Does ext_scaleExchange still work on the correspondingly reduced by distance exchange coupling?

What I want is to have two (or more) thin films separated by varying distances (between different simulations) with varying physical characteristics (this I understand using regions) and sometimes with antiferromagentic layers somewhere in the gap or sometimes sandwiched. Any pointers would be welcome and apologies if this is obvious, I have read through the issues thread and the examples page.

I also would like to say thank you, Mumax3 is an awesome micromagnetic simulator which has helped greatly in my research (single layers so far!!), I hope to have a couple of papers out this year which will credit you guys.

Cheers,

Charlie

**Comment by barnex** [comment]
Please ask general questions like these on the mailing list. The issue tracker is for issues.

**Comment by charliekind** [comment]
Apologies, foolishly thought there was no mailing list as the only one I could find was called mumax2.

**Comment by charliekind** [comment]
Also the point,
'When I initialise a two layer system with nodemag I get the same results in both layers however I set the ext_scaleExchange: positive, negative or zero (DBulk is on and uniform).'
I still don't understand and for me this is an issue, I have tried setting ext_scaleExchange from [-100,100], including zero and the output is always the same. eg.

xStretch := 1 / 2
yStretch := 1 / 2
Nx := 512 * xStretch
Ny := 512 * yStretch
Nz := 2
sizeX := (1024e-9) * xStretch
sizeY := (1024e-9) * yStretch
sizeZ := 1e-9 * Nz
SetGridsize(Nx, Ny, Nz)
SetCellSize(sizeX/Nx, sizeY/Ny, sizeZ/Nz)
Msat = 9e5
Aex = 1e-11
alpha = 0.5
Ku1 = 56e4
Dbulk = 6e-4
EnableDemag = false
defRegion(0, layer(0))
defRegion(1, layer(1))
anisU.setRegion(0, vector(0, 0, 1))
anisU.setRegion(1, vector(0, 0, -1))
m.setRegion(0, Uniform(0, 0, 1))
m.setRegion(1, Uniform(0, 0, -1))
ext_scaleExchange(0, 1, -100)

**Comment by JeroenMulkers** [comment]
Re-ask your questions on the [mailing list](https://groups.google.com/forum/#!forum/mumax2) so that the whole mumax3 community can help you and/or learn from the given answers.

**Comment by charliekind** [comment]
I have applied to join the mailing list, just waiting acceptance, assuming https://groups.google.com/forum/#!forum/mumax2 is the list?
