### ISSUE TITLE
Setting a sine wave geometry 

### ISSUE THREAD

**Issue by AIrodrigo** [mumax/3#168]
Dear Mumax3 community,

I know mumax gives us a certain amount of predetermine shapes ( primitive shapes), however, I would like to know if it is posible to create ripples using a "sine function" instead.
I've been trying to create a 10nm ripple and the only two ways I achieved it is by using cylinders or cuboid, although,for this last one the amount of time required to compile is too long.
Any suggestions?

Cheers,
Rodrigo

**Comment by barnex** [comment]
Please ask general questions like these on the mailing list. The issue tracker is for issues.
