### ISSUE TITLE
Defining Geometry for an Individual Layer

### ISSUE THREAD

**Issue by canerdeger** [mumax/3#169]
Dear all,

Is there any way to set a geometry (e.g. ellipses, rectangles..) for an individual layer?

Because the conventional way desings all defined layers. 

"setgeom( rect(800e-9, 500e-9) )
saveas(geom, "rect")"

Best,

**Comment by JeroenMulkers** [comment]
Please, re-ask this question on the [mailing list](https://groups.google.com/forum/#!forum/mumax2) so that the whole mumax3 community can help you and/or learn from the given answers.

The issue tracker is for issues.
