### ISSUE TITLE
demag kernel gives >100% completion rates

### ISSUE THREAD

**Issue by grahamrow** [mumax/3#17]
When running with 2,2,2 pbcs, for example, the following output is given. Also the simulation typically pauses for a while before beginning — the GUI reports the demag tensor is still being calculated after the command line input has indicated that the calculation is complete.

This is from github source I pulled earlier today.

[Did not use cached kernel: open ../cache/mumax3kernel_[128 128 1]_[2 2 2]_[5e-09 5e-09 6e-10]_6_0 0.ovf: no such file or directory]
Calculating demag kernel 0 %
Calculating demag kernel 25 %
Calculating demag kernel 26 %
Calculating demag kernel 76 %
Calculating demag kernel 77 %
Calculating demag kernel 100 %
Calculating demag kernel 126 %
Calculating demag kernel 127 %

**Comment by kahlos** [comment]
I have **not** had this issue for 3D, has it been fixed?

**Comment by barnex** [comment]
It's still there for 3D PBC I'm afraid.

**Comment by JonathanMaes** [comment]
I can no longer reproduce >100% completion rate when using a grid with the aforementioned dimensions [128 128 1][2 2 2][5e-09 5e-09 6e-10], nor with any other grid I tried. Inspired by this issue, commits 24d8677d52210ab580d57899248ee87249d5896a and 5c59e2f0b71f583e1c5658c62769897ce0018964 were made.

If anyone else has an input script which still gives >100% completion rates, please provide it below.
