### ISSUE TITLE
Hysteresis: just can not output the m.

### ISSUE THREAD

**Issue by qw4894571** [mumax/3#171]
This exmple just can output a table,how can i How can I output the magnetic moment state of each step in the example? Just add a new command "autosave(m)" or others in the end?  Thanks for your time.  And the code as follows.

SetGridsize(128, 32, 1)
SetCellsize(4e-9, 4e-9, 30e-9)

Msat  = 800e3
Aex   = 13e-12

m = randomMag()
relax()         // high-energy states best minimized by relax()

Bmax  := 100.0e-3
Bstep :=  1.0e-3
MinimizerStop = 1e-6
TableAdd(B_ext)

for B:=0.0; B<=Bmax; B+=Bstep{
    B_ext = vector(B, 0, 0)
    minimize()   // small changes best minimized by minimize()
    tablesave()
}

for B:=Bmax; B>=-Bmax; B-=Bstep{
    B_ext = vector(B, 0, 0)
    minimize()   // small changes best minimized by minimize()
    tablesave()
}

for B:=-Bmax; B<=Bmax; B+=Bstep{
    B_ext = vector(B, 0, 0)
    minimize()   // small changes best minimized by minimize()
    tablesave()
}

**Comment by JeroenMulkers** [comment]
Please, re-ask this question on the [mailing list](https://groups.google.com/forum/#!forum/mumax2) so that the whole mumax3 community can help you and/or learn from the given answers.

The issue tracker is for issues.
