### ISSUE TITLE
Differences between relax and minimize in skyrmion stability

### ISSUE THREAD

**Issue by kfqpzzwa91** [mumax/3#173]
Hi all, 

I am trying to simulate a skyrmion confined into a 80-nm wide and 0.4-nm thick nanodot.
I am defining a region of 20 nm as uniform (0,0,1) and uniform(0,0,-1) the rest. 
After that I relax() or minimize() the configuration. 

However, when using relax() I can get a skyrmion but not with minimize. Why is happening this? Which method should I trust? 

Moreover, I also noticed that when I relax() but changing the cellsize( 0.2 nm^2, 0.5 nm^2, 1 nm^2) I stabilize a skyrmion (0.2, 0.5) but not with 1. However, the physics should be independent of the cellsize meanwhile the cellsize is smaller than the exchange length. So, I was wondering If I am really reaching the minimum energy state or not.  

Thanks!

**Comment by kkingstoun** [comment]
I'm using algorithm like this:
relax()
minimize()
run(some time) <- for testing a total energy fluctuation 
relax() <- 
Then I can trust, but not often, it depends. Ther are few things which have to be tested, you never can be sure you state is stable or just probably metastable. 

About the number of the cells through the thickness. Was thickness the same?

Btw, please ask this question here: https://groups.google.com/forum/#!forum/mumax2

**Comment by JeroenMulkers** [comment]
relax and minimize bring you to a local minimum in the energy landscape but they use a very different approach. It is very likely, that in your system, both the ferromagnetic state and a skyrmionic state are stable. Hence, both the minimize and the relax function seem to work correctly in your case.

The physics (which can be described in the micromagnetic framework) should indeed be independent of the cell size. However, in your case, a skyrmion collapses. Such a transition can not be achieved by a continuous deformation of the magnetization. Hence, the collapse of a skyrmion depends on the cell size, but such a transition should not be studied in the micromagnetic framework in the first place.
