### ISSUE TITLE
Are domain wall energy and pinning energy included in Mumax3 ?

### ISSUE THREAD

**Issue by caoyicaoyi** [mumax/3#177]
Hello,
       I am wondering if domain wall energy density and domain wall width (both of them are functions of anisotropy parameter Ku and exchange parameter A) can be considered in Mumax3 simulations. Besides, can I also set a pinning energy density that obstruct the motion of a domain wall in the program? That pinning energy is physically originated from the widely exist defects in sputter prepared thin films. 

Thanks so much!

**Comment by barnex** [comment]
Please use the issue tracker for issues only. General questions can be posted on our forum: https://groups.google.com/forum/#!forum/mumax2. Thanks.
