### ISSUE TITLE
No binary for GPU. Your nvidia driver may be out-of-date

### ISSUE THREAD

**Issue by songchengkun** [mumax/3#178]
Hey,

There is some problems when I using mumax3. My system is Ubuntu 16.04 and GPU is GTX 760, and the NVIDIA-driver 384.111 and CUDA-8.0 are installed successfully. When I type 'mumax3' in the terminal, it shows '**No binary for GPU. Your nvidia driver may be out-of-date**'.  After that, I upgrade the NVIDIA-driver, and the same problem arises. 

What's th problem?

Thanks,

Chengkun

**Comment by NOOBIE140614** [comment]
same issue with me!!

**Comment by JLeliaert** [comment]
This is a problem with the drivers and nothing mumax can change. It can help to downgrade to a slightly older stable driver.
