### ISSUE TITLE
Fatal error: curand.h: No such file or directory

### ISSUE THREAD

**Issue by deparkes** [mumax/3#18]
Hi,
I'm trying to follow the instructions in readme.md.

When I run `go get -u -v github.com/mumax/3/...` I get these errors:

```
# github.com/mumax/3/cuda/curand
/home/deparkes/gocode/src/github.com/mumax/3/cuda/curand/generator.go:3:20: fatal error: curand.h: No such file or directory
 //#include <curand.h>
                    ^
compilation terminated.
# github.com/barnex/cuda5/cufft
/home/deparkes/gocode/src/github.com/barnex/cuda5/cufft/mode.go:3:19: fatal error: cufft.h: No such file or directory
 //#include <cufft.h>
                   ^
compilation terminated.
# github.com/mumax/3/cuda/cufft
/home/deparkes/gocode/src/github.com/mumax/3/cuda/cufft/mode.go:3:19: fatal error: cufft.h: No such file or directory
 //#include <cufft.h>
                   ^
compilation terminated.
```

I was wondering if you had any suggestions for what I could do to solve this?

**Comment by NOOBIE140614** [comment]
Hello, 
I was trying to install the latest version of mumax3 on windows from source code,
and i am getting the same fatal error -- curand.h __no such file ...
I recently installed cuda 9.1 Latest one ....
and its installed in - C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA 
is it possible to migrate the locations in CFOFLAGS to this new one ??
