### ISSUE TITLE
Using Mumax3 via Cygwin on Win10

### ISSUE THREAD

**Issue by OTA-J** [mumax/3#185]
Hello,
I would like to install and use Mumax3 on Windows 10 (64-bit) via Cygwin.
Or if you have a better way to use it on windows, I am all ears.
Many thanks in advance.

**Comment by godsic** [comment]
Mumax3 could be build on Windows natively and we also provide windows builds.

**Comment by OTA-J** [comment]
Hello, 
Thank you for your quick answer. Do you also provide a Windows build for the release 3.9.3 ?

**Comment by godsic** [comment]
@OTA-J see https://github.com/mumax/3/issues/175

**Comment by OTA-J** [comment]
Thank you godsic !
