### ISSUE TITLE
engine.magnetization has no method Add

### ISSUE THREAD

**Issue by pankajmandal4003** [mumax/3#186]
Hello,

I want to add randommag() on top of the magnetization at that instant.  
For eg: m = m.Add(0.1, RandomMagSeed(tim))
Doing this however shows the error: engine.magnetization has no method Add
Which I understand that, I can not use add function on magnetization.

Is there any other possibility to do such an operation. I would be grateful for the solution.
Thanks in advance.

Warm regards

**Comment by JeroenMulkers** [comment]
Please, re-ask this question on the mailing list so that the whole mumax3 community can help you and/or learn from the given answers.

The issue tracker is for issues.
