### ISSUE TITLE
Request: include requisite dll and so files as separate download

### ISSUE THREAD

**Issue by jaxankey** [mumax/3#187]
Feel free to close this ticket if it's a bad idea: 

It would be great if your releases had an optional download for the required .dll and .so files for which mumax is compiled. When my OS's repository upgraded libcufft.so and libcurand.so to version 9, it was a pretty big pain to get these without causing system regressions. (Luckily I had an ubuntu 16.04 system I could use to grab them, and I'm back to happily mumaxing.)

Alternatively, you could offer standalone binaries with all required libraries.

Thanks!
Jack

**Comment by barnex** [comment]
We have considered this for a while, but:
  (1) downloads become inconveniently large,
  (2) you still need to install the nvidia driver, which we cannot bundle. Nvidia bundles CUDA and a compatible driver together. It is arguably easier to just install Nvidia's bundle than to look for a driver which works with the libraries we happen to have bundled.
