### ISSUE TITLE
Cell Size Dependence of final geometry?

### ISSUE THREAD

**Issue by researchAM** [mumax/3#191]
Does cell size play any role in how the final geometry looks?
In the following code, I have kept the simulation domain size constant at 64nm x 64nm x 3 nm. I have varied the no. of cells in x- and y-direction, which in turn varied the cell sizes. No of cells along x-, y- and z-directions are Nx, Ny and Nz. I have kept Nz constant at 1. and varied the ratio between Nx and Ny. I am trying to make an ellipsoid structure with long axis along y-direction. 

// does final geometry depends on Nx/Ny ?

// Define gridsize & cellsize
Ny := 128
Nz := 1
sizeX := 64e-9
sizeY := 64e-9
sizeZ := 3e-9

start := 0.25
loop_step := 0.25
stop := 4

for ratio := start; ratio <= stop; ratio += loop_step{
Nx := ratio*Ny
SetGridSize(Nx, Ny, Nz)
SetCellSize(sizeX/Nx, sizeY/Ny, sizeZ/Nz)

//Define geometry
edgesmooth = 10
ax_major := 18e-09
ax_minor := 12e-09
main_struc := ellipsoid(ax_minor,ax_major,3e-09)
setgeom(main_struc)

//Define regions
defregion(1,main_struc)
save(regions)
}
But I obtained following results-
![regions000000](https://user-images.githubusercontent.com/42718618/45140163-9ae75a80-b1cf-11e8-9e8c-26ea65b02ae5.jpg)
![regions000001](https://user-images.githubusercontent.com/42718618/45140164-9ae75a80-b1cf-11e8-990c-0a145e616c95.jpg)
![regions000002](https://user-images.githubusercontent.com/42718618/45140165-9ae75a80-b1cf-11e8-80e4-94d767dd07da.jpg)
![regions000003](https://user-images.githubusercontent.com/42718618/45140166-9b7ff100-b1cf-11e8-98af-ee49e33423fc.jpg)
![regions000004](https://user-images.githubusercontent.com/42718618/45140167-9b7ff100-b1cf-11e8-94ee-ee8c71976dcd.jpg)
![regions000005](https://user-images.githubusercontent.com/42718618/45140169-9b7ff100-b1cf-11e8-9908-02861a945efd.jpg)
![regions000006](https://user-images.githubusercontent.com/42718618/45140170-9c188780-b1cf-11e8-8854-78413989a3dc.jpg)
![regions000007](https://user-images.githubusercontent.com/42718618/45140171-9c188780-b1cf-11e8-87e6-1454733f8e12.jpg)
![regions000008](https://user-images.githubusercontent.com/42718618/45140172-9c188780-b1cf-11e8-8c4f-578c2774d13a.jpg)
![regions000009](https://user-images.githubusercontent.com/42718618/45140174-9cb11e00-b1cf-11e8-8a36-5645f94e174f.jpg)
![regions000010](https://user-images.githubusercontent.com/42718618/45140175-9cb11e00-b1cf-11e8-80db-173d7c273824.jpg)
![regions000011](https://user-images.githubusercontent.com/42718618/45140176-9cb11e00-b1cf-11e8-9ad7-9c1ea5706450.jpg)
![regions000012](https://user-images.githubusercontent.com/42718618/45140177-9d49b480-b1cf-11e8-9e59-48dc7a44a83b.jpg)
![regions000013](https://user-images.githubusercontent.com/42718618/45140178-9d49b480-b1cf-11e8-8685-75a083661e4c.jpg)
![regions000014](https://user-images.githubusercontent.com/42718618/45140179-9d49b480-b1cf-11e8-9438-b53fcf176c61.jpg)
![regions000015](https://user-images.githubusercontent.com/42718618/45140180-9d49b480-b1cf-11e8-8318-767247af2f59.jpg)
 The 1st image correspond to Nx/Ny = 0.25 and the last image correspond to Nx/Ny = 4 and so on.
From images, it is very clear that the long axis is not along y-axis.
I will be really thankful if you could point out the cause of these erroneous results.
Regards,
AM

**Comment by JeroenMulkers** [comment]
This is not unexpected behaviour. The user is helped [here](https://groups.google.com/forum/#!topic/mumax2/z-218eW9X7E).
