### ISSUE TITLE
Saving sliced quantities does not work when called inside a for loop

### ISSUE THREAD

**Issue by AngusLaurenson** [mumax/3#192]
Sliced output works when in the main body but not when in a loop. There is no error message and the simulation runs to completion. However the .ovf files expected to be saved during execution of the for loop are absent from the output folder.

The script

```
//output directory: example-layers.out/
SetGridsize(128, 32, 32)
SetCellsize(500e-9/128, 125e-9/32, 125e-9/32)
Msat = 800e3
Aex = 13e-12
alpha = 0.02
m.loadfile("m000000.ovf")
save(m)
save(CropZ(m, 16, 17))
save(CropLayer(m_full, 16))
save(m.Comp(2))
B_ext = vector(-24.6E-3, 4.3E-3, 0)
for n := 0; n <= 10; n++ {
	run(1e-10)
	save(CropZ(m, 16, 17))
	save(CropLayer(m_full, 16))
	save(m.Comp(2))
}
```

ls of .out folder

```
gui      m000000.ovf                 m_z000000.ovf          references.bib
log.txt  m_full_zrange16_000000.ovf  m_zrange16_000000.ovf  table.txt
```

**Comment by JeroenMulkers** [comment]
I think that the output files are overwritten in every iteration of the for loop. You can avoid this by defining a crop quantity only once, which you can then save in each iteration.

Something like:

```
crp := CropZ(m, 16, 17)
save(crp)
for n := 0; n <= 10; n++ {
	run(1e-10)
	save(crp)
}
```

Although this might save your problem, I would suggest a more robust approach in which you name the output files yourselves:

```
crp := CropZ(m, 16, 17)
saveas(crp,"crop_init.ovf")
for n :=0 ; n<10; n++ {
    run(1e-12)
    filename = sprintf("crop%.3d.ovf",n) // use the iteration index to numerate the file
    saveas(crp, filename)
}
```
