### ISSUE TITLE
How to defined a ScalarFunction?

### ISSUE THREAD

**Issue by bluove** [mumax/3#193]
We can define a time-dependent B_ext like this:

fmax:=1e9
B_ext.Add(LoadFile("testfile.ovf"), sin(fmax*t))

But if I want to write my  time ScalarFunction, how should I do?
-----------------
I write this, but it is wrong : 

def mytime(t):
	if (t<1e-9) return 1;
	if (t<2e-9) return 2;
	if (t<3e-9) return 2;

B_ext.Add(LoadFile("testfile.ovf"),mytime(t))

**Comment by JeroenMulkers** [comment]
Please, re-ask this question on the mailing [list](https://groups.google.com/forum/#!forum/mumax2) so that the whole mumax3 community can help you and/or learn from the given answers.

The issue tracker is for issues.

**Comment by bluove** [comment]
Thanks，I have already submitted my application

Sent from YoMail
