### ISSUE TITLE
How to compile mumax3 in Win10?

### ISSUE THREAD

**Issue by Kohei7655** [mumax/3#207]
I edited source code of Mumax3 but I don't know how to compile it and start a simulation. Can you teach me the way to compile?

**Comment by kkingstoun** [comment]
I think you can find the answer here:

https://groups.google.com/forum/#!searchin/mumax2/windows%7Csort:date

Please let me know if you have any questions, please text me: mateusz.zelent@amu.edu.pl

**Comment by Kohei7655** [comment]
Thank you for your kind answer. I'll join it.
