### ISSUE TITLE
How can I create many folders with one .mx3 file?

### ISSUE THREAD

**Issue by kksg0201** [mumax/3#208]
Recently, I used mumax3 program with For structure for convenience.
However, I got a problem because all of .ovf files have been saved in one folder.

I have tried to solve with function FilenameFormat. But it created other problems like such impossible to understand file names below.

something.ovf%!(EXTRA string=m, int=0)   something.ovf%!(EXTRA string=m, int=4)
something.ovf%!(EXTRA string=m, int=1)   something.ovf%!(EXTRA string=m, int=5)

Could you help me?

**Comment by barnex** [comment]
Question has been answered on the mailing list.
