### ISSUE TITLE
doubt about the space between two regions

### ISSUE THREAD

**Issue by Mc210** [mumax/3#211]
I would like to study the interaction between 2 distant materials. In oommf the world size is defined through the atlas, but in Mumax3 one defines only the regions that depend on the size and location of the object, The total size of the simulation is not defined by an instructions.

If 2 geometries are created in 2 distant regions, automatically mumax3 assumes that these 2 are in the same box and therefore interact through the magnetostatic field?

**Comment by barnex** [comment]
Let's keep general questions for the mailing list: https://groups.google.com/forum/#!forum/mumax2.
The issue tracker is for issues.

But yes, all magnets in the simulation box will interact magnetostatically.
