### ISSUE TITLE
Weird problem when read m from .ovf file

### ISSUE THREAD

**Issue by mdai26** [mumax/3#214]
After one simulaiton, I output a magnetization distribuion file myfile.ovf. When I try to use this magnetization distribution to start a new simulation, I typed m.loadfile("myfile.ovf") and then mumax3.exe flashed back immediately. The version I use is mumax3.9.1_windows and my default web browser is google chrome. I am wondering how I can solve this issue.

**Comment by JeroenMulkers** [comment]
What exactly do you mean by 'flashed back'?
Can you provide both scripts?

**Comment by mdai26** [comment]
Hi,


Thank you so much for your kind reply. I mean when I run the mumax3.exe and type command "m.loadfile("myfile.ovf")", mumax3.exe will stop running and a disconnected sign will show on the web page. The screen shot of the problem is below.

[cid:8a287f75-dad5-41c9-adae-1f770fc67be6]

I just entered this command.

[cid:06e85340-fea3-472f-839a-06e82b835e72]

And then mumax3.exe stop running.


I didn't use any script but just type a command.


Best regards.


Minyi



________________________________

**Comment by mdai26** [comment]
I found this problem can be solved by using command line to run mumax3.exe rather than using the interactive mode. Now the m file can be read normally.
