### ISSUE TITLE
How to use mumax3-server

### ISSUE THREAD

**Issue by Mc210** [mumax/3#215]
I have a server based on linux that does not have a graphical interface. I would like to use mumax3-server to view the files that are running.

In the server i put:

mumax3-server

2018/12/14 13:29:06 serving at zt:35360
2018/12/14 13:29:06 serving at 127.2.3.1:35360
2018/12/14 13:29:06 serving at [::1]:35360
2018/12/14 13:29:20 -- portscan done

when I try to enter  the ip direction http://server-ip:35360 from another computer, the browser shows that the connection has expired.

I have to do something extra?

**Comment by Mc210** [comment]
It's very strange, it does not work.

**Comment by zhouxzh** [comment]
Maybe you need to consider about your network configuration.
What about your router setting?
Sometime, the firmware can block the port accession, or the router is not allow you to access the port.
One possible solution is that you ask the administrator.
Or you could think about use the ssh tunnel to forward the Mumax3-server port to your local computer. 


Dr. Xianzhong Zhou
Guangdong University of Technology
Guangzhou, China
zhouxzh@gdut.edu.cn
