### ISSUE TITLE
How to use mumax3-script

### ISSUE THREAD

**Issue by solwave** [mumax/3#218]
I would like to use mumax3-script to parse parameter values using stdin.
The idea being, I would like to run a batch simulation process by changing the value of a parameter.
So how do I go about this,

**Comment by JeroenMulkers** [comment]
Please, re-ask this question on the mailing [list](https://groups.google.com/forum/#!forum/mumax2) so that the whole mumax3 community can help you and/or learn from the given answers.

The issue tracker is for issues.
