### ISSUE TITLE
load geometry from ovf file

### ISSUE THREAD

**Issue by Mc210** [mumax/3#237]
I have saved the geometry using the savesas (geom, "geometry") command. Is it possible to load the geometry through some instruction?.

Thanks

**Comment by JeroenMulkers** [comment]
The issue tracker is for issues only. You can use the mumax mailing list (https://groups.google.com/forum/#!forum/mumax2) for general usage questions. On this mailing list the whole mumax3 community can help you by answering your questions and/or learn from the given answers.
