### ISSUE TITLE
Any differences in version 3.9.3 and version 3.10beta will lead to different result with the exactly same input txt 

### ISSUE THREAD

**Issue by yjzhang97** [mumax/3#239]
The input txt:
`setgridsize(10, 10, 1)`
`setcellsize(4e-9, 4e-9, 2e-9)`
`setGeom(cylinder(40e-9, 2e-9))`
`Msat = 1e6`
`Aex = 2e-11`
`alpha = 0.0003`
`m = uniform(0, 0.8, 1)`
`lambda = 1.5`
`epsilonprime = 0.083`
`Pol = 0.6`
`fixedlayer = vector(0, 0, 1)`
`B_ext = vector(0, 0, 5e-1)`
`J = vector(0, 0, -4e9)`
`tableautosave(1e-11)`
`run(4e-9)`

The result in 3.9.3 version:
[3.9.3.txt](https://github.com/mumax/3/files/3614697/3.9.3.txt)
![3 9 3](https://user-images.githubusercontent.com/43169876/64933840-a60ca600-d879-11e9-8a70-2efa917d033c.png)

The result in 3.10 beta version:
[3.10beta.txt](https://github.com/mumax/3/files/3614702/3.10beta.txt)
![3 10](https://user-images.githubusercontent.com/43169876/64933856-bcb2fd00-d879-11e9-8ced-5ecf2a4260b2.png)

Considering the change sign of the epsilonprime in version 3.10beta, we applied minus epsilonprime, but the result is still different as following:

[3.10beta-differ.txt](https://github.com/mumax/3/files/3614707/3.10beta-differ.txt)
![3 10_differ](https://user-images.githubusercontent.com/43169876/64933992-76aa6900-d87a-11e9-88c2-9d5683cdf127.PNG)

Any changes in version 3.10 we ignored cause these result? Or what's wrong with our code or settings?

**Comment by JeroenMulkers** [comment]
This is due to a bugfix in 3.10. See discussion in https://github.com/mumax/3/issues/99 for more information.
