### ISSUE TITLE
Gold Antenna Above Magnetic Film

### ISSUE THREAD

**Issue by Synergy0** [mumax/3#244]
I'm working on a project where I have a long thin strip of magnetic material with a gold antenna that lies on top of the strip at a 90 degree angle.  There is an AC current going through the gold antenna at 9.5GHz which should generate spin waves in the strip.  Is there a way in Mumax of modeling the gold antenna as a non-magnetic material that will generate the appropriate fields in the strip below?

**Comment by kkingstoun** [comment]
Hi, you can do it using comsol and then implement it to the mumax.

Mateusz

czw., 14 lis 2019, 23:28 użytkownik Synergy0 <notifications@github.com>
napisał:

**Comment by JeroenMulkers** [comment]
For a simple antenna, you should be able to calculate the magnetic field analytically.

If you have more questions on how to use mumax3, please use the [mailing list](https://groups.google.com/forum/#!forum/mumax2). The issue tracker is for issues only.
