### ISSUE TITLE
Issue with regions.LoadFile in OVF1_TEXT format

### ISSUE THREAD

**Issue by MoellerMarcel** [mumax/3#245]
I'm trying to load a previously saved regions file in OVF1_TEXT format and get the following error message "_panic: strconv.ParseFloat: parsing "": invalid syntax_".

I added a minimal example with which I could reproduce the issue in mumax3.9.1c and mumax3.10beta2. Additionally, I added the complete console output.

For testing first run bug_setup.txt and then bug_test.txt.

The OVF2_TEXT format worked fine for me (as shown in the example).

[bug_setup.txt](https://github.com/mumax/3/files/3875369/bug_setup.txt)
[bug_test.txt](https://github.com/mumax/3/files/3875370/bug_test.txt)
[console_output.txt](https://github.com/mumax/3/files/3875365/console_output.txt)

**Comment by JeroenMulkers** [comment]
Nice catch.

The ovf1 file supports only 3d-vector fields. The 'region field' has only one component, which means that it shouldn't be saved in the ovf1 format in the first place.

I added a check to make sure that only 3d vector fields are saved in the ovf1 format ( see 2ae87b948).
