### ISSUE TITLE
Dipole Field Question

### ISSUE THREAD

**Issue by MagGuy1** [mumax/3#259]
Hi all.  I had a question. 

Using Mumax, is it possible to output the dipolar fields that would be measured by a sensor placed above(or in) a thin film?

**Comment by DeSanz** [comment]
Hi, you could maybe define a region, and then export the field in that region doing something like:
`save(B_demag.Region(1))`

**Comment by JeroenMulkers** [comment]
Have a look at the MFM example on https://mumax.github.io/examples.html

If you have more questions about the usage of mumax3, please ask them on the [mailing list](https://groups.google.com/forum/#!forum/mumax2). The issue tracker is for issues only.
