### ISSUE TITLE
large gridsize bug when using cuda11

### ISSUE THREAD

**Issue by JeroenMulkers** [mumax/3#268]
**Bug description:**

The following input script
```
N := 512
setGridSize(N,N,1)
setCellSize(1,1,1)
save(B_demag)
```
gives the following error
```
panic: CUDA_ERROR_INVALID_VALUE
github.com/mumax/3/cuda/cu.MemsetD32Async(0xb1c000000, 0xc000000000, 0x100000, 0x0)
        C:/Users/jmulkers/GO/src/github.com/mumax/3/cuda/cu/memset.go:25 +0x126
```
when mumax3.10 is build against cuda11. Simulations with smaller grid sizes (e.g. for `N:=256`) run fine. This error does not occur in builds against older cuda versions.

**Environment**

- System: Windows 10
- Nvidia driver: 451.22
- GPU: Titan RTX
- CUDA version: 11.0

**Comment by godsic** [comment]
@JeroenMulkers I ran `bench.mx3` on 970, 980 Ti, 1080 and Titan Xp but the issue never showed up. Have you reproduced with most recent CUDA 11.0 Update 1 and on Linux?

**Comment by JeroenMulkers** [comment]
This recent update for CUDA11.0 seems to resolve the issue on windows! @godsic thank you for pointing out that there has been an update

@JLeliaert , can you confirm that [this windows build](https://mumax.ugent.be/mumax3-binaries/mumax3.10_windows_cuda11.0.zip) does not have the bug that you reported to me?

**Comment by JLeliaert** [comment]
confirmed

**Comment by JeroenMulkers** [comment]
Building mumax3.10 against cuda11.0.3 (update 1) instead of cuda11.0.1 solves this issue on both windows and linux.

The binaries on the mumax.ugent.be are updated, and the download links are active again.

**Comment by askeyjw** [comment]
Hello, I am using CUDA driver 11.2, driver version 461.40 and windows 10 but am getting this error even after uninstalling and re-installing mumax3.10. Not quite sure what I'm doing wrong!
