### ISSUE TITLE
go install fails with golang 1.16

### ISSUE THREAD

**Issue by mgidding** [mumax/3#288]
Hi, when I try to install mumax3 (version 3.10) with go 1.16.2 I get the following error:

`maxime@maxime-desktop mumax3 % go install 
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
`

The exact same command works fine with go 1.15.10 however, resulting in a working mumax3 binary.

**Comment by godsic** [comment]
@mgidding Starting with go 1.16 use of modules is mandatory. Until mumax3 is converted to go module, you can workaround by running `go mod init` in mumax3 root folder and then compile / install it as usual.
