### ISSUE TITLE
MUMAX3 3.9.1:  Some parameters cause disconnection

### ISSUE THREAD

**Issue by LIMZ0052** [mumax/3#290]
Hi all,
I am new to MUMAX3. I am using version 3.9.1 in Windows 10.

I have two examples of parameters that cause MUMAX3 disconnection:
1. Setting any nonzero value to temp
2. Setting the same nonzero value to Dind and Dbulk, for example, 1e-3.

Could anybody please advise me how to solve this problem?
Thanks!

**Comment by godsic** [comment]
@LIMZ0052 Please check out [mumax3.10](https://mumax.github.io/download.html). If you still experience the same issues, then please provide more details for further investigation, e.g., logs, example mx3 scripts, etc.
