### ISSUE TITLE
About array

### ISSUE THREAD

**Issue by hhm-call** [mumax/3#293]
How to define an m*n array?

**Comment by JonathanMaes** [comment]
The mumax³ scripting language does not support arrays.
mumax³ can also run actual `.go` scripts, as is done in a few examples in the `test/` directory, though this functionality is largely undocumented. Such a `.go` would allow arrays, as such scripts can use the full functionality of Go.
The [mumax³ mailing list](https://groups.google.com/g/mumax2) may contain more information on this subject: a [similar question](https://groups.google.com/g/mumax2/c/bJO0oIpVaow/m/SG48EXJoAQAJ) was recently posed there.
