### ISSUE TITLE
Minor typo in API for sinc function- says return 0 if x=0

### ISSUE THREAD

**Issue by JLauzier** [mumax/3#308]
Hello,

There is a small typo in the API description for the sinc function

"Sinc returns sin(x)/x. If x=0, then Sinc(x) returns 0."

Should be 

"Sinc returns sin(x)/x. If x=0, then Sinc(x) returns 1."

It's correct in the internal mumax documentation/implementation, just a minor (and obvious) typo on the API page.

**Comment by JLeliaert** [comment]
Fixed
