### ISSUE TITLE
High Performance Computing (HPC) conf. suggestion - node/tasks

### ISSUE THREAD

**Issue by zkhodzhaev** [mumax/3#313]
Hello,

As I know Mumax runs in GPU, and it only uses 1 node/ script. So, I can't distribute 1 script into different nodes at the same time.
So, I am trying to find out what configuration in Slurm gives the best performance in Mumax (my tests were inconsistent - errors).

Ex: (1. Can Mumax distribute script into tasks? or i should just use -N 1)

#SBATCH -n 4         # number of tasks per node
#SBATCH -N 1         # total number of mpi tasks requested
#SBATCH -p gpu-a100              # Queue name
#SBATCH -t 4:00:00       # Run time 

Thank you for your help.

**Comment by jedcheng** [comment]
Saw your question when looking for something else.
Have you resolved the problem?

Although I don't understand your problem, my usual practice is to generate a bunch of scripts with a generator using a range of parameters (for example the length of an object). 

Then I would launch 16 independent jobs simultaneously to quickly sweep through parameters on the HPC.

**Comment by zkhodzhaev** [comment]
Thank you for your feedback. I was looking for a more in-script solution.

**Comment by JonathanMaes** [comment]
This appears to be a practical issue which depends on the architecture of a specific HPC.
As suggested by @jedcheng, sweeping through parameters with a bunch of scripts, or by using an overarching script in another programming language which generates such scripts, is likely a more versatile solution.
