### ISSUE TITLE
rebase the nonlocalRKKY feature to the current master code

### ISSUE THREAD

**Issue by yaudl** [mumax/3#318]
Hello, 

Is it possible for the nonlocalRKKY feature to be rebased against the current master code and wrap around cuda 11?

**Comment by JonathanMaes** [comment]
The `feature/nonlocalRKKY` branch does not appear to contain any comment referring to a specific paper by which we can verify its implementation. Therefore, we can not merge this feature at the present time.

**Comment by JonathanMaes** [comment]
The `feature/nonlocalRKKY` branch does not appear to contain any comment referring to a specific paper by which we can verify its implementation. Therefore, we can not merge this feature at the present time.
