### ISSUE TITLE
Running error "/log.txt: no such file or directory"

### ISSUE THREAD

**Issue by zkhodzhaev** [mumax/3#320]
Hi,

What could be the reason for this error (running on HPC): 

//output directory: 227.158.Ku0p743e6_pol0p4_40ns_1500ns_temp223_strip1p3_Ku0p3_jan9227.out/
//mumax 3.10 [linux_amd64 go1.14(gc) CUDA-11.0]
//GPU info: NVIDIA A100-PCIE-40GB(40536MB), CUDA Driver 11.4, cc=8.0, using cc=80 PTX
//(c) Arne Vansteenkiste, Dynamat LAB, Ghent University, Belgium
//This is free software without any warranty. See license.txt
//********************************************************************//
//  If you use mumax in any work or publication,                      //
//  we kindly ask you to cite the references in references.bib        //
//********************************************************************//
//output directory: 227.158.Ku0p743e6_pol0p4_40ns_1500ns_temp223_strip1p3_Ku0p3_jan9227.out/
panic: open 227.158.Ku0p743e6_pol0p4_40ns_1500ns_temp223_strip1p3_Ku0p3_jan9227.out/log.txt: no such file or directory

goroutine 1 [running, locked to thread]:
github.com/mumax/3/engine.initLog()
	/home/jmulkers/GO/src/github.com/mumax/3/engine/log.go:63 +0x1e9
github.com/mumax/3/engine.InitIO(0x7ffd3a5d59c0, 0x47, 0xc00039a2d0, 0x48, 0x0)
	/home/jmulkers/GO/src/github.com/mumax/3/engine/od.go:45 +0x17d
main.runScript(0x7ffd3a5d59c0, 0x47)
	/home/jmulkers/GO/src/github.com/mumax/3/cmd/mumax3/main.go:101 +0xd6
main.runFileAndServe(0x7ffd3a5d59c0, 0x47)
	/home/jmulkers/GO/src/github.com/mumax/3/cmd/mumax3/main.go:92 +0x67
main.main()
	/home/jmulkers/GO/src/github.com/mumax/3/cmd/mumax3/main.go:59 +0x179
panic: open 227.158.Ku0p743e6_pol0p4_40ns_1500ns_temp223_strip1p3_Ku0p3_jan9227.out/log.txt: no such file or directory

**Comment by MathieuMoalic** [comment]
Hi,

It might be you don't have write permission to the `227.158.Ku0p743e6_pol0p4_40ns_1500ns_temp223_strip1p3_Ku0p3_jan9227.out` directory. Did you try deleting the directory before starting the simulation ? Could it be because the name is too long ? ( probably not but it's worth checking )

**Comment by zkhodzhaev** [comment]
Thank you for your response.

1. I am checking the long name 
2. It creates the .out file:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/21960382/211820062-1c2676e0-13cd-41e9-b780-6b2da18d8005.png">

I don't know why, but, every time I am getting different errors, this is from the previous run (I am using mask):

<img width="550" alt="image" src="https://user-images.githubusercontent.com/21960382/211820720-f5df78ee-0986-4ee8-96a6-30e50fb07510.png">

**Comment by zkhodzhaev** [comment]
Ok, I don't know why, but, shortening the name worked.

**Comment by zkhodzhaev** [comment]
Also, it is good to hear you Mathieu
