### ISSUE TITLE
Feature: record minimum dt

### ISSUE THREAD

**Issue by syockit** [mumax/3#37]
In OOMMF's `thetaevolve`, user is advised to first run the simulation at 0 K, enabling adaptive-step evaluation. And then, the lower boundary is used as the fixed dt value in finite temperature simulation.

Having an option to save the smallest step over all time steps (as done with `peakErr`) would be nice.

By the way, would it expensive to add another comparison check in `adaptDt`? It'd be nice if golang supported metaprogramming…

**Comment by barnex** [comment]
Addressed by #131, no more need to determine min dt.
