### ISSUE TITLE
Watchdog prematurely kills jobs if servers are not sync in time.

### ISSUE THREAD

**Issue by syockit** [mumax/3#42]
This is on mumax3.7a commit e7c58ad860b275fd886d910f9a5b560610f08708

Sometimes my servers have their clocks not in sync, one being late by more than half a minute.
The last seen alive time is written by the server running the job, but watchdog on the server hosting the job compares the time with its own server clock, so it will kill the job prematurely.

For now I'll work around it by ensuring the time is sync'ed correctly (might be due to ntpd not functioning in order)

**Comment by barnex** [comment]
Closing as this is unlikely to be fixed. Note that everything works well with clock drifts < 30s, easily achievable with NTP.
