### ISSUE TITLE
Feature Request: Time-Dependent Anisotropy Constant

### ISSUE THREAD

**Issue by xfong** [mumax/3#43]
I am trying to simulate voltage-controlled magnetic anisotropy and was wondering is MuMax3 supports time-dependent anisotropy constants. If not, could that be easily integrated into MuMax3?

Thanks,
Kelvin

**Comment by barnex** [comment]
It's already there. See the docs or test files.

**Comment by xfong** [comment]
Just to clarify, if I use:
Ku1 = scaleFac*t/1e-9
Then, MuMax3 computes Ku1 at every time step and use that accordingly?

**Comment by mumax** [comment]
yes.
