### ISSUE TITLE
mumax3-server 3.7  fails to start

### ISSUE THREAD

**Issue by ivlis** [mumax/3#44]
mumax3-server complains that the port is already in use. This happens for any port

    [ivlis@ou-dell2 mumax3_scripts]$ /opt/mumax3/mumax3.7_linux/mumax3-server -exec /opt/mumax3/mumax3.7_linux/mumax3-cuda7.0 -l :60000
    2015/05/05 07:56:01 have //mumax 3.7 linux_amd64 go1.4.2 (gc)
    2015/05/05 07:56:02 gpu 0 : //mumax 3.7 linux_amd64 go1.4.2 (gc)
    //CUDA 7000 GeForce GTX 780 Ti(3071MB) cc3.5, using CC35 PTX 
    //(c) Arne Vansteenkiste, Dynamat LAB, Ghent University, Belgium
    //This is free software without any warranty. See license.txt
    CUDA 7000 GeForce GTX 780 Ti(3071MB) cc3.5
    2015/05/05 07:56:02 LoadUserJobs 1
    2015/05/05 07:56:02 serving at ou-dell2:60000
    2015/05/05 07:56:02 listen tcp 141.210.115.253:60000: bind: address already in use

It happens with any port, even if mumax3 is run under root. There is no other servers on this PC:

    [ivlis@ou-dell2 mumax3_scripts]$ netstat -lnpt 
    (Not all processes could be identified, non-owned process info
     will not be shown, you would have to be root to see it all.)
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
    tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      -                   
    tcp6       0      0 :::5355                 :::*                    LISTEN      -       

The most interesting thing is that, in a very rear case (maybe 1:20) the server does start! I cannot figure out the conditions on that.

**Comment by barnex** [comment]
fixed

**Comment by ivlis** [comment]
It seems that we have to open the issue, as in 3.8 the same problem presents. Just upgraded from my patched version.

**Comment by kahlos** [comment]
I still have this problem too, my workaround is to specify IP:Port
> mumax3-server -l 192.168.1.9:35360
