### ISSUE TITLE
[feature request] Turn 'FixedLayer' into vector field

### ISSUE THREAD

**Issue by godsic** [mumax/3#50]
Anders Eklund:
"Since our devices present inhomogeneous fields and hence polarizer magnetizations (for the fixed layer magnetization at 30 mA, theta has a spatial deviation +/- 5 deg and phi +/- 15 deg) it would obviously be an advantage to be able to account for this in the most realistic way."

**Comment by godsic** [comment]
@barnex 
https://github.com/mumax/3/commit/7ea09bebe3466956f644808c366d359385db36e1

**Comment by godsic** [comment]
https://github.com/mumax/3/commit/7ea09bebe3466956f644808c366d359385db36e1

**Comment by godsic** [comment]
@barnex https://github.com/mumax/3/commit/7ea09bebe3466956f644808c366d359385db36e1

**Comment by barnex** [comment]
All tests pass, merged into master.
