### ISSUE TITLE
 CUDA_ERROR_INVALID_IMAGE

### ISSUE THREAD

**Issue by kkingstoun** [mumax/3#54]
When i try to use minimize() function, mumax has crashed and showed me a this error:

(Only when i'm using mimize(), relax() works fine)

Win 7 64-bit GTX 980 TI  MSI Lightening 

//mumax 3.9c windows_amd64 go1.3.3 (gc)
//CUDA 7050 GeForce GTX 980 Ti(6144MB) cc5.2, using CC52 PTX
//(c) Arne Vansteenkiste, Dynamat LAB, Ghent University, Belgium
//This is free software without any warranty. See license.txt
//output directory: .\test.out/
//starting GUI at http://127.0.0.1:35367
SetGridsize(128, 32, 1)
SetCellsize(4e-9, 4e-9, 30e-9)
Msat = 800e3
Aex = 13e-12
m = randomMag()
B_ext = vector(0, 1, 0)
relax()
//Not using kernel cache (-cache="")
// Calculating demag kernel 1 %
// Calculating demag kernel 100 %
Bmax := 100.0e-3
Bstep := 1.0e-3
MinimizerStop = 1e-6
TableAdd(B_ext)
for B := 0.0; B <= Bmax; B += Bstep {
        B_ext = vector(B, 0, 0)
        minimize()
        tablesave()
}
panic: CUDA_ERROR_INVALID_IMAGE
goroutine 16 [running]:
runtime.panic(0x8ae900, 0xc8)
        c:/go/src/pkg/runtime/panic.c:279 +0x11f
github.com/mumax/3/cuda/cu.ModuleLoadData(0x0, 0x0, 0x34)
        C:/Users/Arne/src/github.com/mumax/3/cuda/cu/module.go:31 +0x87
github.com/mumax/3/cuda.fatbinLoad(0xc08205cb10, 0x9a46b0, 0x8, 0x8e4de0)
        C:/Users/Arne/src/github.com/mumax/3/cuda/fatbin.go:12 +0x6f
github.com/mumax/3/cuda.k_minimize_async(0x23062c0000, 0x23062c4000, 0x23062c8000, 0x23062ec000, 0x23062e8000, 0x23062e4
000, 0x23062e0000, 0x23062dc000, 0x23062d8000, 0x38d1b717, ...)
        C:/Users/Arne/src/github.com/mumax/3/cuda/minimize_wrapper.go:64 +0xd7
github.com/mumax/3/cuda.Minimize(0xc08317eaa0, 0xc08385a4b0, 0xc08385a230, 0x38d1b717)
        C:/Users/Arne/src/github.com/mumax/3/cuda/minimize.go:16 +0x235
github.com/mumax/3/engine.(*Minimizer).Step(0xc0837de700)
        C:/Users/Arne/src/github.com/mumax/3/engine/minimizer.go:69 +0x13b
github.com/mumax/3/engine.step(0x7ec401)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:196 +0x3a
github.com/mumax/3/engine.runWhile(0xc0820576e8, 0xc08385a201)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:181 +0x95
github.com/mumax/3/engine.RunWhile(0xc0820576e8)
        C:/Users/Arne/src/github.com/mumax/3/engine/run.go:172 +0x40
github.com/mumax/3/engine.Minimize()
        C:/Users/Arne/src/github.com/mumax/3/engine/minimizer.go:157 +0x2fe
reflect.Value.call(0x7ffda0, 0xa75a90, 0x0, 0x130, 0x971130, 0x4, 0xd66698, 0x0, 0x0, 0x0, ...)
        c:/go/src/pkg/reflect/value.go:563 +0x1217

**Comment by godsic** [comment]
Please update mumax to the most recent version.

**Comment by kkingstoun** [comment]
I'm don't how to compile mumax on windows? Could you send me a new compiled version for windows?

**Comment by godsic** [comment]
@barnex Arne do you still have a toolchain to make Windows builds?

**Comment by barnex** [comment]
Yeah, I uploaded 3.9.1_windows. I cannot verify that it works, so please
let me know. Also my windows virtual machine seems to be dying so I may not
be able to make builds for much longer.

**Comment by kkingstoun** [comment]
It's working fine now thanks!

**Comment by barnex** [comment]
You're welcome.
