### ISSUE TITLE
mumax3-server memory leak after many simulations are run

### ISSUE THREAD

**Issue by syockit** [mumax/3#55]
Recently I discovered that `mumax3-server` memory usage bloats after a large number of simulations. My colleague had around 700~ mx3 files in his folder.

From the head of the output of is `pprof/heap`:

    heap profile: 184: 3070230816 [9190: 3247059856] @ heap/1048576
    183: 3070230528 [183: 3070230528] @ 0x42874c 0x49357e 0x40215d 0x40bbbc 0x437561
    #	0x49357e	github.com/mumax/3/httpfs.Create+0x2ce	/home/syukri/gopath/src/github.com/mumax/3/httpfs/reader.go:21
    #	0x40215d	main.NewProcess+0x8ed			/home/syukri/gopath/src/github.com/mumax/3/cmd/mumax3-server/compute.go:164
    #	0x40bbbc	main.func·003+0x14c			/home/syukri/gopath/src/github.com/mumax/3/cmd/mumax3-server/compute.go:70

where line 21 of `httpfs/reader.go` is
```go
    	return &bufWriter{bufio.NewWriterSize(&appendWriter{URL, 0}, BUFSIZE)}, nil
```
To dissect the problem, I modified `reader.go` to the following
```go
    	mywriter := &appendWriter{URL, 0}
    	mybufio := bufio.NewWriterSize(mywriter, BUFSIZE)
    	return &bufWriter{mybufio}, nil
```
and recompiled, and ran the server on another folder with 10 simulation files. This time, the head of `pprof/heap` read:

    heap profile: 13: 167862608 [24: 167937288] @ heap/1048576
    10: 167772160 [10: 167772160] @ 0x4289dc 0x493811 0x40215d 0x40be40 0x4377f1
    #	0x493811	github.com/mumax/3/httpfs.Create+0x2d1	/home/syukri/gopath/src/github.com/mumax/3/httpfs/reader.go:22
    #	0x40215d	main.NewProcess+0x8ed			/home/syukri/gopath/src/github.com/mumax/3/cmd/mumax3-server/compute.go:166
    #	0x40be40	main.func·003+0x2a0			/home/syukri/gopath/src/github.com/mumax/3/cmd/mumax3-server/compute.go:72

Line 22 refers to
```go
    	mybufio := bufio.NewWriterSize(mywriter, BUFSIZE)
```
It puzzles me why this one escapes the GC; it seems this one is alive even after reference to the parent Process is deleted (line 65 of `cmd/mumax3-server/compute.go`).

P/S: Compiled on Linux kernel 3.2.0-4-amd64 using golang 1.4.2

**Comment by syockit** [comment]
Problem persists on golang 1.5.2

    heap profile: 101: 1677721984 [134: 1678039600] @ heap/1048576
    100: 1677721600 [100: 1677721600] @ 0x4505c5 0x4b4926 0x402561 0x40cd1b 0x46dfc1
    #	0x4b4926	github.com/mumax/3/httpfs.Create+0x286	/home/syukri/gopath/src/github.com/mumax/3/httpfs/reader.go:21
    #	0x402561	main.NewProcess+0x991			/home/syukri/gopath/src/github.com/mumax/3/cmd/mumax3-server/compute.go:164
    #	0x40cd1b	main.RunComputeService.func1+0xcb	/home/syukri/gopath/src/github.com/mumax/3/cmd/mumax3-server/compute.go:70

Granted, most of them are virtual, and only a little percentage are reserved, but they do build up. My colleague's server has 914M RSS now after restarting yesterday.

Apparently, `nil`ing `buf` allows it to be GC'ed.

    // httpfs/reader.go
    func (w *bufWriter) Close() error                {
     err := w.buf.Flush() 
     if err != nil {
     	return err
     }
     w.buf = nil
     return nil
    }

for which the profile now reads

    heap profile: 2: 528 [138: 1677918648] @ heap/1048576
    ... snip ...
    0: 0 [100: 1677721600] @ 0x4505c5 0x4b4926 0x402561 0x40cd1b 0x46dfc1
    #	0x4b4926	github.com/mumax/3/httpfs.Create+0x286	/home/syukri/gopath/src/github.com/mumax/3/httpfs/reader.go:21
    #	0x402561	main.NewProcess+0x991			/home/syukri/gopath/src/github.com/mumax/3/cmd/mumax3-server/compute.go:164
    #	0x40cd1b	main.RunComputeService.func1+0xcb	/home/syukri/gopath/src/github.com/mumax/3/cmd/mumax3-server/compute.go:70

I still don't understand: why is the explicit `nil`ing necessary even when no references to it survive?

**Comment by barnex** [comment]
Hmm, this looks like I might be keeping a pointer to the bufWriter somewhere. nilling the buffer frees most of its memory but may not fix the root cause.
Anyway, feel free to send a pull request with your mitigation if you like (but perhaps move the w.buf=nil up to before the if).
I'd be very surprised if this is a go GC issue.
