### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by zelgatis** [mumax/3#58]
Hi,

While running simulations, I constantly get Cuda error message. It is something like "CUDA illegal instructions", "Unknwon CU result: 700". It happens not only at the beginning of the simulation, but also at the middle or towards the end. How do I resolve this issue? Thank you.

**Comment by barnex** [comment]
This has only been correlated with flaky hardware, typically overclocked GPUs. Try down clocking in nvidia-settings. This has worked for us on gtx760s.

**Comment by zelgatis** [comment]
Thanks for the reply. I tried setting both the core clock and memory clock at their minimum values using "Afterburner". It helps, but still the simulation crashes in the middle of the run.

**Comment by barnex** [comment]
Closing, as this is an nvida hardware issue. Several less unfortunate users have been able to get their GPU stable at a lower clock frequency.
