### ISSUE TITLE
Bsat value unused in ext_rmSurfaceCharge

### ISSUE THREAD

**Issue by syockit** [mumax/3#63]
In `engine/ext_rmsurfacecharge.go`, the function `compensateLRSurfaceCharges` has `bsat` as a parameter, but is unused.

Shouldn't line 42 be multiplied with `bsat`?

    q := cell[Z] * cell[Y] * bsat

**Comment by barnex** [comment]
Good catch, thanks! Verified and fixed in:
94fb4b77757e8d1d1cb76b98bd52cec796a148ef
36e5b0e1f7d966af6a592506ffbe26dfc5f5f1eb
