### ISSUE TITLE
SetRegionFuncGo, SetRegionValueGo - Missing Methods?

### ISSUE THREAD

**Issue by kahlos** [mumax/3#67]
I've been trying to define material parameters as a function with little success. I'm not sure what they do, but in the API I see two methods:
> SetRegionFuncGo( int func() float64 )
> SetRegionValueGo( int float64 )

When I try to call them on the MSat parameter, I get an error as follows:
> //script line 1: MSat.SetRegionFuncGo(): *engine.ScalarParam has no method SetRegionFuncGo
> //script line 1: MSat.SetRegionValueGo(): *engine.ScalarParam has no method SetRegionValueGo

Any ideas what they do and why they don't work in the example above? Any suggestions as to how I might vary my material parameters without using regions? The motivation is to simulate the effects of reduced magnetisation length from a temperature distribution.

Note, something similar is discussed in issue #15, the loading of parameters is not implemented.

**Comment by syockit** [comment]
They are meant to be used with `golang`. I don't know why it is unaccessible from script, but it shouldn't be anyway.

Unfortunately, there is no support for spatial variation of material parameter, other than using regions. Maybe a feature extension to allow choice of using regions or mesh for each parameter could be programmed, but that would be a lot of work. (If I'm not mistaken, this was how `mumax2` worked. It took lots of memory as a mesh of size N will allocate array of size N for each quantity involved which has space-dependent values. `mumax3` uses lookup table instead)

**Comment by barnex** [comment]
Those methods *are* available in mx3 scripts, they're just called
setregion. In pure Go there's no overloading so we need distinct names,
that's all.
