### ISSUE TITLE
Dzyaloshinskii-Moriya interaction

### ISSUE THREAD

**Issue by AGKolesnikov** [mumax/3#68]
I've trying to define the bilayer film with different DMI in each layer. For this goal two regions were defined as top and bottom layers. Then magnetic parameters were set for this two regions. The values of magnetisatoin saturation (Msat) and exchange stiffness (Aex) were identical for top and bottom layers, but the Interfacial Dzyaloshinskii-Moriya strength (Dind) was different for each layer. After the compilation I get the error message "DMI: Msat, Aex, Dex must be uniform". Why DMI should be uniform for all regions? The function Dind has method "SetRegion( int ScalarFunction )" as written in syntax. How I can solve this problem and define special DMI for each region?

**Comment by peynmurray** [comment]
You can define DMI for individual regions, but you need to call ext_EnableUnsafe() before you do so. See unsafe_dmi.mx3 for an example. Note that the results won't necessarily be reliable (you're calling ext_EnableUnsafe() after all).

**Comment by barnex** [comment]
I believe @JeroenMulkers has a fix in for this.
