### ISSUE TITLE
autosave and autosnapshot of the same quaitnity are not possible

### ISSUE THREAD

**Issue by godsic** [mumax/3#71]
As reported by Teng Sun and @syockit , one cannot use simultaneously autosave and autosnaphot of the same quantity. This is because they share the same output que (`output`) and quantity (`q`), i.e. 

`output[q] = &autosave{period, Time, -1, save}.`

**Comment by barnex** [comment]
I'm not sure if this is worth fixing. One can autosave and then use mumax3-convert to make snapshots. Autosnapshot is a redundant feature requested by users reluctant to save the full data.
