### ISSUE TITLE
Periodic boundary conditions not working if number of cells are odd numbers in the x direction.

### ISSUE THREAD

**Issue by FGarcias** [mumax/3#74]
I have the following error when I use an odd number for the Nx cell and I use periodic boundary conditions. I think there is a small error in some integer division.

Below there is a typical example. There is a mismatch in the fft length.

If it the example I exchange x by y does not happen because 182 is an even number. Whenever Nx is odd and PBC are on in that direction I get the error.

//mumax 3.9.1c linux_amd64 go1.3.3 (gc)
//CUDA 8000 GeForce GT 640(2047MB) cc3.0, using CC30 PTX 
//(c) Arne Vansteenkiste, Dynamat LAB, Ghent University, Belgium
//This is free software without any warranty. See license.txt
//output directory: array_red.out/
//starting GUI at http://127.0.0.1:35367
Nx := 105
Ny := 182
Nz := 32
lx := 105e-9
ly := 182e-9
lz := 32e-9
dx := lx / Nx
dy := ly / Ny
dz := lz / Nz
SetPBC(3, 3, 0)
SetGridSize(Nx, Ny, Nz)
SetCellSize(dx, dy, dz)
m = uniform(0, 0.1, 1)
Msat = 1.4e6
Aex = 1.3e-11
Ku1 = 4.5e5
Ku2 = 1.5e5
anisU = vector(0, 0, 1)
save(B_demag)
//Not using kernel cache (-cache="")
// Calculating demag kernel 49 %
// Calculating demag kernel 73 %
// Calculating demag kernel 99 %
// Calculating demag kernel 100 %
fft size mismatch: expecting dst len 1246336, got 1234688
panic: fft size mismatch: expecting dst len 1246336, got 1234688

goroutine 16 [running]:
runtime.panic(0x7ebd60, 0xc2096a7690)
    /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
log.Panicf(0x9fefd0, 0x2f, 0xc209121128, 0x2, 0x2)
    /usr/lib/go/src/pkg/log/log.go:314 +0xcd
github.com/mumax/3/cuda.(_fft3DR2CPlan).ExecAsync(0xc20911c2c0, 0xc2090cc910, 0xc2090cc820)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/cuda/fft3dr2c.go:41 +0x254
github.com/mumax/3/cuda.(_DemagConvolution).init(0xc20911c200, 0xc209180050, 0xc2091805a0, 0xc209180a00, 0xc2091805a0, 0xc209181720, 0xc2090cc280, 0xc209180a00, 0xc2090cc280, 0xc2090cd180)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/cuda/conv_demag.go:159 +0x65e
github.com/mumax/3/cuda.NewDemag(0x69, 0xb6, 0x20, 0x3, 0x3, 0x0, 0xc209180050, 0xc2091805a0, 0xc209180a00, 0xc2091805a0, ...)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/cuda/conv_demag.go:28 +0xf0
github.com/mumax/3/engine.demagConv(0x0)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/demag.go:116 +0x308
github.com/mumax/3/engine.SetDemagField(0xc209181e00)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/demag.go:52 +0x4c
github.com/mumax/3/engine.(__setter).Set(0xf80400, 0xc209181e00)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/setter.go:27 +0x30
github.com/mumax/3/engine.(__setter).Slice(0xf80400, 0x0, 0xc20918bc00)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/setter.go:22 +0xc1
github.com/mumax/3/engine.SaveAs(0x7ffbf31fae60, 0xf80400, 0xc20918bc20, 0x1f)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/save.go:69 +0x238
github.com/mumax/3/engine.Save(0x7ffbf31fae60, 0xf80400)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/save.go:55 +0xf9
reflect.Value.call(0x7fad60, 0xa5d738, 0x0, 0x130, 0x95d9b0, 0x4, 0xc20918bbc0, 0x1, 0x1, 0x0, ...)
    /usr/lib/go/src/pkg/reflect/value.go:563 +0x1210
reflect.Value.Call(0x7fad60, 0xa5d738, 0x0, 0x130, 0xc20918bbc0, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/lib/go/src/pkg/reflect/value.go:411 +0xd7
github.com/mumax/3/script.(*call).Eval(0xc2080b4330, 0x0, 0x0)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/script/call.go:61 +0x256
github.com/mumax/3/engine.EvalFile(0xc2080b4120)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/script.go:99 +0x1e0
main.runFileAndServe(0x7ffcf079a54c, 0xd)
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/cmd/mumax3/main.go:144 +0x1da
main.main()
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/cmd/mumax3/main.go:89 +0x2bf

goroutine 19 [finalizer wait]:
runtime.park(0x41b8e0, 0xf7deb0, 0xf68a69)
    /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xf7deb0, 0xf68a69)
    /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
github.com/mumax/3/engine.runSaver()
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/asyncio.go:40 +0x50
created by github.com/mumax/3/engine.init·2
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/asyncio.go:24 +0x9c

goroutine 17 [syscall]:
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 33 [IO wait]:
net.runtime_pollWait(0x7ffbf3205788, 0x72, 0x0)
    /usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(_pollDesc).Wait(0xc2091080d0, 0x72, 0x0, 0x0)
    /usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(_pollDesc).WaitRead(0xc2091080d0, 0x0, 0x0)
    /usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(_netFD).accept(0xc209108070, 0xa5e290, 0x0, 0x7ffbf31fa418, 0xb)
    /usr/lib/go/src/pkg/net/fd_unix.go:419 +0x343
net.(_TCPListener).AcceptTCP(0xc2090d4160, 0xc2090dc6a8, 0x0, 0x0)
    /usr/lib/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(_TCPListener).Accept(0xc2090d4160, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
net/http.(_Server).Serve(0xc2090f2060, 0x7ffbf32047e0, 0xc2090d4160, 0x0, 0x0)
    /usr/lib/go/src/pkg/net/http/server.go:1698 +0x91
net/http.Serve(0x7ffbf32047e0, 0xc2090d4160, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go/src/pkg/net/http/server.go:1576 +0x7c
github.com/mumax/3/engine.func·085()
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/gui.go:537 +0x38
created by github.com/mumax/3/engine.GoServe
    /home/felipe/mumax_versions/mumax_3.9.1/src/github.com/mumax/3/engine/gui.go:537 +0x2e3

**Comment by hamedvakilit** [comment]
The odd number of cells in X direction won't work when you use PBC condition in x direction.
But using for example, SetPBC(0, 3, 0), works fine.

**Comment by JeroenMulkers** [comment]
Fixed in 4fe9c988
