### ISSUE TITLE
exchange bias between layers

### ISSUE THREAD

**Issue by jandrewsgomes** [mumax/3#75]
how do I implement an exchange bias in mumax?
I can get through the DMI?

**Comment by vichou8005** [comment]
I have the same question

**Comment by barnex** [comment]
Exchange bias is equivalent to an applied field. If desired you can apply the field to only, e.g., the bottom layer. You can find a more elaborate example here: "Modelling exchange bias with MuMax3" http://iopscience.iop.org/article/10.1088/0022-3727/49/43/435001/pdf
