### ISSUE TITLE
Remove magnetic surface charge in PMA infinite wires

### ISSUE THREAD

**Issue by prashanthr30** [mumax/3#76]
The ext_rmSurfaceCharge function works only for in-plane magnetized systems. Is there a function to remove magnetic surface charge to simulate infinitely long wire with perpendicular anisotropy?

**Comment by barnex** [comment]
There is no such method built-in. You can, however, calculate and save the demag field of a uniform PMA film, oppositely magnetized to you film of interest. Then, in a second simulation, add this field as an external field. This has the exact same effect as removing the surface charges.
