### ISSUE TITLE
mumax3-convert fail when use *.ovf

### ISSUE THREAD

**Issue by xgstation** [mumax/3#81]
When I type such command
`mumax3-convert -png *.ovf`
it shows
`[fail] .ovf     -> .png: GetFileAttributesEx .ovf: The system cannot find the file specified.
0 files converted,  0 skipped,  1 failed`
while there are ovf files in same directory, and if I specify the file name like this way
`mumax3-convert -png m000001.ovf`
it will work.

OS: Windows 10.0.14393.0

**Comment by kkingstoun** [comment]
Windows PowerShell or CMD doesn't understand *. You have to write a script with for loop or do it manually.

**Comment by JeroenMulkers** [comment]
kkingstoun is right. Unlike unix shells, the cmd interpreter of Windows does not expand wildcards such as *. 

However, I modified the code of mumax3-convert in such a way that it can handle wildcards by itself. See pull request #82

**Comment by godsic** [comment]
merged #82
