### ISSUE TITLE
Issue in setting current in different region

### ISSUE THREAD

**Issue by hsuxx295** [mumax/3#84]
Hi,
I tried to defined current for different region by using j.setregion.
ex. 
j.setregion( 1, vector(1e12, 0, 0) )  
j.setregion( 2, vector(0, 0, 1e12) )
If I save(J), there will be value in .ovf file. But in simulation there is no current flowing . If I snapshot(J), it shows no current.

If I only have an universal j = vector(1e12, 0, 0), there will be a flow chart shown when I snapshot(J) (indicating there's current flow).

Any possible solution?
Thank you.

**Comment by JeroenMulkers** [comment]
Can you give a minimal input script which demonstrates your problem?

A small note about snapshots: If a vector quantity is zero everywhere, then the snapshot will be grey. A white or black snapshot indicates a nonzero z-component.

**Comment by hsuxx295** [comment]
SetGridsize(600, 200, 1)
SetCellsize(1e-9, 1e-9, 1e-9)

EdgeSmooth = 16
setgeom( rect(600e-9,200e-9) )
defregion(1, xrange(-300e-9, 0))

m = uniform(1, 0, 0)
Msat = 500e3
Aex = 1.5e-11
alpha = 0.3
Ku1 = 0.8e6
Dind = 3.5e-3
Xi = 0.3
AnisU = vector(0, 0, 1)

J = vector(-8e12, 0, 0) 
J.setregion(1,vector(-5e-12, 0, 0))
snapshot(J)


![image](https://cloud.githubusercontent.com/assets/17911900/20020288/98109c96-a29e-11e6-8dca-1aa23b8d6056.png)

**Comment by hsuxx295** [comment]
Problem is solved now. Thank you.
