### ISSUE TITLE
Installing Mumax on Windows 7?

### ISSUE THREAD

**Issue by SebasTF** [mumax/3#88]
Hi,
I installed Mumax on a new computer with Windows 7 Home Premium, it has graphics card Nvidia gtx 1060 and CUDA version 6.5..
However, when I try to run the program, I get the message Mumax has stopped working.

Could you help me?
Thanks,
Sebastian

**Comment by barnex** [comment]
You have to run mumax from the command line. Could you copy-paste the terminal output?

**Comment by SebasTF** [comment]
Yes, I did. That message appears after this ouput.
//Not using kernel cache (-cache="")
The command screen turns gray and just let me close the program, then cmd show me as if process is over.
I have another PC with Windows 7 Home Premium, but with grafics card Nvidia gtx 770 and same CUDA.
In this latest computer, Mumax works perfectly.

**Comment by barnex** [comment]
The provided information is insufficient to start troubleshooting. If the issue persists, feel free to re-open and provide *full* terminal output, not just the last line.

**Comment by Macielakis** [comment]
I have the same problem, I have tried 5 times and is always dvcuda.dll is not found. and install 3 more program as nvidia monitor or Visual studio from Microsoft nothing I tried help
