### ISSUE TITLE
Compound Geometries

### ISSUE THREAD

**Issue by JJVentham** [mumax/3#92]
I'm trying to create a geometry consisting of a Cylinder mounted on a cuboid using the .add command however it seems that if you try to construct geometries from parts that don't span the entire z dimension the GUI just shows up as empty space.

This is the script I have been trying to use:

[YIG8-PY-p115.txt](https://github.com/mumax/3/files/729336/YIG8-PY-p115.txt)

Is there a way to get this working?

**Comment by JeroenMulkers** [comment]
The cylinder is inside the cuboid. As a result, there is not a single cell in region 1 after you defined region 2.

When you define shapes, remember that they are placed at the origin of the universe (this is the center of the simulation box) by default.

**Comment by JJVentham** [comment]
Much Appreciated!
