### ISSUE TITLE
2 layer thick simulations

### ISSUE THREAD

**Issue by JJVentham** [mumax/3#98]
I am trying to simulate a disc on top of a plane, each 1 cell thick. My issue is that I do not know how the origin is defined for when you have a mesh that is 2 cells thick. I have tried shifting the plane and the disc around in multiple configurations but it either crashes or just gives a disc in the top layer and empty space underneath. To define the disc I have tried both the Circle and Cylinder in built functions.

As a work around I have also tried defining the same geometry in a mesh that is 3 cells thick with a layer of empty space beneath. This seemed to work however when I loaded a magnetization state in rather than using a state from one of the predefined mumax uniform state, the geometry just comes up as disc in the top layer and two layers of empty space underneath.

**Comment by JLeliaert** [comment]
This is a minimally working example of what you want to do:


SetMesh(64, 64, 2, 10e-9,10e-9,10e-9, 0, 0, 0)

a:=cuboid(640e-9, 640-9,20e-9).transl(0,0,-10e-9)
b:=cylinder(320e-9, 10e-9).transl(0,0,10e-9)
setgeom(a.add(b))

m=uniform (1,1,0)
Relax()

**Comment by JJVentham** [comment]
I just tried the same idea adjusted for my problem but got the same issue, a cylinder on the top with empty space beneath. 

Here is my script:

SetMesh(256,1024,2,4.5e-9,4.5e-9,1.5e-8,16,16,0)
a:=cuboid(256*4.5e-9, 1024*4.5e-9,15e-9).transl(0,0,-15e-9)
b:=cylinder(351e-9, 15e-9).transl(0,0,15e-9)
setgeom(a.add(b)

**Comment by JLeliaert** [comment]
SetMesh(256,1024,2,4.5e-9,4.5e-9,1.5e-8,16,16,0)
a:=cuboid(256*4.5e-9, 1024*4.5e-9,*30e-9*).transl(0,0,-15e-9)
b:=cylinder(351e-9, 15e-9).transl(0,0,15e-9)
setgeom(a.add(b))

This should work

**Comment by JJVentham** [comment]
Thanks! Much appreciated.
